// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_views.proto

package x

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PB_PostView struct {
	PostId         int64        `protobuf:"varint,1,opt,name=PostId" json:"PostId,omitempty"`
	UserId         int32        `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
	PostTypeEnum   PostTypeEnum `protobuf:"varint,3,opt,name=PostTypeEnum,enum=PostTypeEnum" json:"PostTypeEnum,omitempty"`
	Text           string       `protobuf:"bytes,4,opt,name=Text" json:"Text,omitempty"`
	RichText       string       `protobuf:"bytes,5,opt,name=RichText" json:"RichText,omitempty"`
	MediaCount     int32        `protobuf:"varint,6,opt,name=MediaCount" json:"MediaCount,omitempty"`
	SharedTo       int32        `protobuf:"varint,7,opt,name=SharedTo" json:"SharedTo,omitempty"`
	DisableComment int32        `protobuf:"varint,8,opt,name=DisableComment" json:"DisableComment,omitempty"`
	HasTag         int32        `protobuf:"varint,9,opt,name=HasTag" json:"HasTag,omitempty"`
	CommentsCount  int32        `protobuf:"varint,10,opt,name=CommentsCount" json:"CommentsCount,omitempty"`
	LikesCount     int32        `protobuf:"varint,11,opt,name=LikesCount" json:"LikesCount,omitempty"`
	ViewsCount     int32        `protobuf:"varint,12,opt,name=ViewsCount" json:"ViewsCount,omitempty"`
	EditedTime     int32        `protobuf:"varint,13,opt,name=EditedTime" json:"EditedTime,omitempty"`
	CreatedTime    int32        `protobuf:"varint,14,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	ReSharedPostId int64        `protobuf:"varint,15,opt,name=ReSharedPostId" json:"ReSharedPostId,omitempty"`
	// With me
	DidILiked        bool            `protobuf:"varint,50,opt,name=DidILiked" json:"DidILiked,omitempty"`
	DidIReShared     bool            `protobuf:"varint,51,opt,name=DidIReShared" json:"DidIReShared,omitempty"`
	SenderUserView   *PB_UserView    `protobuf:"bytes,100,opt,name=SenderUserView" json:"SenderUserView,omitempty"`
	ReSharedUserView *PB_UserView    `protobuf:"bytes,101,opt,name=ReSharedUserView" json:"ReSharedUserView,omitempty"`
	MediaView        *PB_MediaView   `protobuf:"bytes,102,opt,name=MediaView" json:"MediaView,omitempty"`
	MediaViewList    []*PB_MediaView `protobuf:"bytes,103,rep,name=MediaViewList" json:"MediaViewList,omitempty"`
}

func (m *PB_PostView) Reset()                    { *m = PB_PostView{} }
func (m *PB_PostView) String() string            { return proto.CompactTextString(m) }
func (*PB_PostView) ProtoMessage()               {}
func (*PB_PostView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

func (m *PB_PostView) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PB_PostView) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_PostView) GetPostTypeEnum() PostTypeEnum {
	if m != nil {
		return m.PostTypeEnum
	}
	return PostTypeEnum_POST_RESHARED
}

func (m *PB_PostView) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PB_PostView) GetRichText() string {
	if m != nil {
		return m.RichText
	}
	return ""
}

func (m *PB_PostView) GetMediaCount() int32 {
	if m != nil {
		return m.MediaCount
	}
	return 0
}

func (m *PB_PostView) GetSharedTo() int32 {
	if m != nil {
		return m.SharedTo
	}
	return 0
}

func (m *PB_PostView) GetDisableComment() int32 {
	if m != nil {
		return m.DisableComment
	}
	return 0
}

func (m *PB_PostView) GetHasTag() int32 {
	if m != nil {
		return m.HasTag
	}
	return 0
}

func (m *PB_PostView) GetCommentsCount() int32 {
	if m != nil {
		return m.CommentsCount
	}
	return 0
}

func (m *PB_PostView) GetLikesCount() int32 {
	if m != nil {
		return m.LikesCount
	}
	return 0
}

func (m *PB_PostView) GetViewsCount() int32 {
	if m != nil {
		return m.ViewsCount
	}
	return 0
}

func (m *PB_PostView) GetEditedTime() int32 {
	if m != nil {
		return m.EditedTime
	}
	return 0
}

func (m *PB_PostView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_PostView) GetReSharedPostId() int64 {
	if m != nil {
		return m.ReSharedPostId
	}
	return 0
}

func (m *PB_PostView) GetDidILiked() bool {
	if m != nil {
		return m.DidILiked
	}
	return false
}

func (m *PB_PostView) GetDidIReShared() bool {
	if m != nil {
		return m.DidIReShared
	}
	return false
}

func (m *PB_PostView) GetSenderUserView() *PB_UserView {
	if m != nil {
		return m.SenderUserView
	}
	return nil
}

func (m *PB_PostView) GetReSharedUserView() *PB_UserView {
	if m != nil {
		return m.ReSharedUserView
	}
	return nil
}

func (m *PB_PostView) GetMediaView() *PB_MediaView {
	if m != nil {
		return m.MediaView
	}
	return nil
}

func (m *PB_PostView) GetMediaViewList() []*PB_MediaView {
	if m != nil {
		return m.MediaViewList
	}
	return nil
}

type PB_MediaView struct {
	MediaId       int64  `protobuf:"varint,1,opt,name=MediaId" json:"MediaId,omitempty"`
	UserId        int32  `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
	PostId        int32  `protobuf:"varint,3,opt,name=PostId" json:"PostId,omitempty"`
	AlbumId       int32  `protobuf:"varint,4,opt,name=AlbumId" json:"AlbumId,omitempty"`
	MediaTypeEnum int32  `protobuf:"varint,5,opt,name=MediaTypeEnum" json:"MediaTypeEnum,omitempty"`
	Width         int32  `protobuf:"varint,6,opt,name=Width" json:"Width,omitempty"`
	Height        int32  `protobuf:"varint,7,opt,name=Height" json:"Height,omitempty"`
	Size          int32  `protobuf:"varint,8,opt,name=Size" json:"Size,omitempty"`
	Duration      int32  `protobuf:"varint,9,opt,name=Duration" json:"Duration,omitempty"`
	Color         string `protobuf:"bytes,10,opt,name=Color" json:"Color,omitempty"`
	CreatedTime   int32  `protobuf:"varint,11,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
}

func (m *PB_MediaView) Reset()                    { *m = PB_MediaView{} }
func (m *PB_MediaView) String() string            { return proto.CompactTextString(m) }
func (*PB_MediaView) ProtoMessage()               {}
func (*PB_MediaView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1} }

func (m *PB_MediaView) GetMediaId() int64 {
	if m != nil {
		return m.MediaId
	}
	return 0
}

func (m *PB_MediaView) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_MediaView) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PB_MediaView) GetAlbumId() int32 {
	if m != nil {
		return m.AlbumId
	}
	return 0
}

func (m *PB_MediaView) GetMediaTypeEnum() int32 {
	if m != nil {
		return m.MediaTypeEnum
	}
	return 0
}

func (m *PB_MediaView) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PB_MediaView) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PB_MediaView) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PB_MediaView) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *PB_MediaView) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *PB_MediaView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

type PB_ActionView struct {
	ActionId              int64           `protobuf:"varint,1,opt,name=ActionId" json:"ActionId,omitempty"`
	ActorUserId           int32           `protobuf:"varint,2,opt,name=ActorUserId" json:"ActorUserId,omitempty"`
	ActionTypeEnum        int32           `protobuf:"varint,3,opt,name=ActionTypeEnum" json:"ActionTypeEnum,omitempty"`
	PeerUserId            int32           `protobuf:"varint,4,opt,name=PeerUserId" json:"PeerUserId,omitempty"`
	PostId                int64           `protobuf:"varint,5,opt,name=PostId" json:"PostId,omitempty"`
	CommentId             int64           `protobuf:"varint,6,opt,name=CommentId" json:"CommentId,omitempty"`
	Murmur64Hash          int64           `protobuf:"varint,7,opt,name=Murmur64Hash" json:"Murmur64Hash,omitempty"`
	CreatedTime           int32           `protobuf:"varint,8,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	ActorUserView         *PB_UserView    `protobuf:"bytes,100,opt,name=ActorUserView" json:"ActorUserView,omitempty"`
	PostView              *PB_PostView    `protobuf:"bytes,101,opt,name=PostView" json:"PostView,omitempty"`
	CommentView           *PB_CommentView `protobuf:"bytes,102,opt,name=CommentView" json:"CommentView,omitempty"`
	FollowedUserView      *PB_UserView    `protobuf:"bytes,103,opt,name=FollowedUserView" json:"FollowedUserView,omitempty"`
	ContentOwenerUserView *PB_UserView    `protobuf:"bytes,104,opt,name=ContentOwenerUserView" json:"ContentOwenerUserView,omitempty"`
}

func (m *PB_ActionView) Reset()                    { *m = PB_ActionView{} }
func (m *PB_ActionView) String() string            { return proto.CompactTextString(m) }
func (*PB_ActionView) ProtoMessage()               {}
func (*PB_ActionView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{2} }

func (m *PB_ActionView) GetActionId() int64 {
	if m != nil {
		return m.ActionId
	}
	return 0
}

func (m *PB_ActionView) GetActorUserId() int32 {
	if m != nil {
		return m.ActorUserId
	}
	return 0
}

func (m *PB_ActionView) GetActionTypeEnum() int32 {
	if m != nil {
		return m.ActionTypeEnum
	}
	return 0
}

func (m *PB_ActionView) GetPeerUserId() int32 {
	if m != nil {
		return m.PeerUserId
	}
	return 0
}

func (m *PB_ActionView) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PB_ActionView) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *PB_ActionView) GetMurmur64Hash() int64 {
	if m != nil {
		return m.Murmur64Hash
	}
	return 0
}

func (m *PB_ActionView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_ActionView) GetActorUserView() *PB_UserView {
	if m != nil {
		return m.ActorUserView
	}
	return nil
}

func (m *PB_ActionView) GetPostView() *PB_PostView {
	if m != nil {
		return m.PostView
	}
	return nil
}

func (m *PB_ActionView) GetCommentView() *PB_CommentView {
	if m != nil {
		return m.CommentView
	}
	return nil
}

func (m *PB_ActionView) GetFollowedUserView() *PB_UserView {
	if m != nil {
		return m.FollowedUserView
	}
	return nil
}

func (m *PB_ActionView) GetContentOwenerUserView() *PB_UserView {
	if m != nil {
		return m.ContentOwenerUserView
	}
	return nil
}

type PB_NotifyView struct {
	NotifyId      int64           `protobuf:"varint,1,opt,name=NotifyId" json:"NotifyId,omitempty"`
	ForUserId     int32           `protobuf:"varint,2,opt,name=ForUserId" json:"ForUserId,omitempty"`
	ActorUserId   int32           `protobuf:"varint,3,opt,name=ActorUserId" json:"ActorUserId,omitempty"`
	NotiyTypeEnum int32           `protobuf:"varint,4,opt,name=NotiyTypeEnum" json:"NotiyTypeEnum,omitempty"`
	PostId        int64           `protobuf:"varint,5,opt,name=PostId" json:"PostId,omitempty"`
	CommentId     int64           `protobuf:"varint,6,opt,name=CommentId" json:"CommentId,omitempty"`
	PeerUserId    int32           `protobuf:"varint,7,opt,name=PeerUserId" json:"PeerUserId,omitempty"`
	Murmur64Hash  int64           `protobuf:"varint,8,opt,name=Murmur64Hash" json:"Murmur64Hash,omitempty"`
	SeenStatus    int32           `protobuf:"varint,9,opt,name=SeenStatus" json:"SeenStatus,omitempty"`
	CreatedTime   int32           `protobuf:"varint,10,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	ActorUserView *PB_UserView    `protobuf:"bytes,100,opt,name=ActorUserView" json:"ActorUserView,omitempty"`
	PostView      *PB_PostView    `protobuf:"bytes,101,opt,name=PostView" json:"PostView,omitempty"`
	CommentView   *PB_CommentView `protobuf:"bytes,102,opt,name=CommentView" json:"CommentView,omitempty"`
}

func (m *PB_NotifyView) Reset()                    { *m = PB_NotifyView{} }
func (m *PB_NotifyView) String() string            { return proto.CompactTextString(m) }
func (*PB_NotifyView) ProtoMessage()               {}
func (*PB_NotifyView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{3} }

func (m *PB_NotifyView) GetNotifyId() int64 {
	if m != nil {
		return m.NotifyId
	}
	return 0
}

func (m *PB_NotifyView) GetForUserId() int32 {
	if m != nil {
		return m.ForUserId
	}
	return 0
}

func (m *PB_NotifyView) GetActorUserId() int32 {
	if m != nil {
		return m.ActorUserId
	}
	return 0
}

func (m *PB_NotifyView) GetNotiyTypeEnum() int32 {
	if m != nil {
		return m.NotiyTypeEnum
	}
	return 0
}

func (m *PB_NotifyView) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PB_NotifyView) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *PB_NotifyView) GetPeerUserId() int32 {
	if m != nil {
		return m.PeerUserId
	}
	return 0
}

func (m *PB_NotifyView) GetMurmur64Hash() int64 {
	if m != nil {
		return m.Murmur64Hash
	}
	return 0
}

func (m *PB_NotifyView) GetSeenStatus() int32 {
	if m != nil {
		return m.SeenStatus
	}
	return 0
}

func (m *PB_NotifyView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_NotifyView) GetActorUserView() *PB_UserView {
	if m != nil {
		return m.ActorUserView
	}
	return nil
}

func (m *PB_NotifyView) GetPostView() *PB_PostView {
	if m != nil {
		return m.PostView
	}
	return nil
}

func (m *PB_NotifyView) GetCommentView() *PB_CommentView {
	if m != nil {
		return m.CommentView
	}
	return nil
}

type PB_CommentView struct {
	CommentId      int64        `protobuf:"varint,1,opt,name=CommentId" json:"CommentId,omitempty"`
	UserId         int32        `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
	PostId         int64        `protobuf:"varint,3,opt,name=PostId" json:"PostId,omitempty"`
	Text           string       `protobuf:"bytes,4,opt,name=Text" json:"Text,omitempty"`
	LikesCount     int32        `protobuf:"varint,5,opt,name=LikesCount" json:"LikesCount,omitempty"`
	CreatedTime    int32        `protobuf:"varint,6,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	SenderUserView *PB_UserView `protobuf:"bytes,15,opt,name=SenderUserView" json:"SenderUserView,omitempty"`
}

func (m *PB_CommentView) Reset()                    { *m = PB_CommentView{} }
func (m *PB_CommentView) String() string            { return proto.CompactTextString(m) }
func (*PB_CommentView) ProtoMessage()               {}
func (*PB_CommentView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{4} }

func (m *PB_CommentView) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *PB_CommentView) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_CommentView) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PB_CommentView) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PB_CommentView) GetLikesCount() int32 {
	if m != nil {
		return m.LikesCount
	}
	return 0
}

func (m *PB_CommentView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_CommentView) GetSenderUserView() *PB_UserView {
	if m != nil {
		return m.SenderUserView
	}
	return nil
}

type PB_UserView struct {
	UserId             int32         `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	UserName           string        `protobuf:"bytes,2,opt,name=UserName" json:"UserName,omitempty"`
	FirstName          string        `protobuf:"bytes,4,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName           string        `protobuf:"bytes,5,opt,name=LastName" json:"LastName,omitempty"`
	UserTypeEnum       UserTypeEnum  `protobuf:"varint,6,opt,name=UserTypeEnum,enum=UserTypeEnum" json:"UserTypeEnum,omitempty"`
	UserLevelEnum      UserLevelEnum `protobuf:"varint,7,opt,name=UserLevelEnum,enum=UserLevelEnum" json:"UserLevelEnum,omitempty"`
	AvatarId           int64         `protobuf:"varint,8,opt,name=AvatarId" json:"AvatarId,omitempty"`
	ProfilePrivacyEnum int32         `protobuf:"varint,9,opt,name=ProfilePrivacyEnum" json:"ProfilePrivacyEnum,omitempty"`
	Phone              int64         `protobuf:"varint,10,opt,name=Phone" json:"Phone,omitempty"`
	About              string        `protobuf:"bytes,11,opt,name=About" json:"About,omitempty"`
	// counters 100 - 200
	FollowersCount int32 `protobuf:"varint,100,opt,name=FollowersCount" json:"FollowersCount,omitempty"`
	FollowingCount int32 `protobuf:"varint,101,opt,name=FollowingCount" json:"FollowingCount,omitempty"`
	PostsCount     int32 `protobuf:"varint,102,opt,name=PostsCount" json:"PostsCount,omitempty"`
	MediaCount     int32 `protobuf:"varint,103,opt,name=MediaCount" json:"MediaCount,omitempty"`
	LikesCount     int32 `protobuf:"varint,104,opt,name=LikesCount" json:"LikesCount,omitempty"`
	ResharedCount  int32 `protobuf:"varint,105,opt,name=ResharedCount" json:"ResharedCount,omitempty"`
	// last activities
	UserOnlineStatusEnum UserOnlineStatusEnum `protobuf:"varint,200,opt,name=UserOnlineStatusEnum,enum=UserOnlineStatusEnum" json:"UserOnlineStatusEnum,omitempty"`
	LastActiveTime       int32                `protobuf:"varint,201,opt,name=LastActiveTime" json:"LastActiveTime,omitempty"`
	// with me
	MyFollwing FollowingEnum `protobuf:"varint,300,opt,name=MyFollwing,enum=FollowingEnum" json:"MyFollwing,omitempty"`
}

func (m *PB_UserView) Reset()                    { *m = PB_UserView{} }
func (m *PB_UserView) String() string            { return proto.CompactTextString(m) }
func (*PB_UserView) ProtoMessage()               {}
func (*PB_UserView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{5} }

func (m *PB_UserView) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_UserView) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PB_UserView) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PB_UserView) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PB_UserView) GetUserTypeEnum() UserTypeEnum {
	if m != nil {
		return m.UserTypeEnum
	}
	return UserTypeEnum_USER
}

func (m *PB_UserView) GetUserLevelEnum() UserLevelEnum {
	if m != nil {
		return m.UserLevelEnum
	}
	return UserLevelEnum_LEVEL_NORMAL
}

func (m *PB_UserView) GetAvatarId() int64 {
	if m != nil {
		return m.AvatarId
	}
	return 0
}

func (m *PB_UserView) GetProfilePrivacyEnum() int32 {
	if m != nil {
		return m.ProfilePrivacyEnum
	}
	return 0
}

func (m *PB_UserView) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *PB_UserView) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *PB_UserView) GetFollowersCount() int32 {
	if m != nil {
		return m.FollowersCount
	}
	return 0
}

func (m *PB_UserView) GetFollowingCount() int32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *PB_UserView) GetPostsCount() int32 {
	if m != nil {
		return m.PostsCount
	}
	return 0
}

func (m *PB_UserView) GetMediaCount() int32 {
	if m != nil {
		return m.MediaCount
	}
	return 0
}

func (m *PB_UserView) GetLikesCount() int32 {
	if m != nil {
		return m.LikesCount
	}
	return 0
}

func (m *PB_UserView) GetResharedCount() int32 {
	if m != nil {
		return m.ResharedCount
	}
	return 0
}

func (m *PB_UserView) GetUserOnlineStatusEnum() UserOnlineStatusEnum {
	if m != nil {
		return m.UserOnlineStatusEnum
	}
	return UserOnlineStatusEnum_EXACTLY
}

func (m *PB_UserView) GetLastActiveTime() int32 {
	if m != nil {
		return m.LastActiveTime
	}
	return 0
}

func (m *PB_UserView) GetMyFollwing() FollowingEnum {
	if m != nil {
		return m.MyFollwing
	}
	return FollowingEnum_FOLLOWING_NONE
}

type PB_TopProfileView struct {
	User *PB_UserView `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
}

func (m *PB_TopProfileView) Reset()                    { *m = PB_TopProfileView{} }
func (m *PB_TopProfileView) String() string            { return proto.CompactTextString(m) }
func (*PB_TopProfileView) ProtoMessage()               {}
func (*PB_TopProfileView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{6} }

func (m *PB_TopProfileView) GetUser() *PB_UserView {
	if m != nil {
		return m.User
	}
	return nil
}

// used for list of users in like/followings/followers list
type PB_UserViewRowify struct {
	Id          int64        `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	CreatedTime int32        `protobuf:"varint,2,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	UserView    *PB_UserView `protobuf:"bytes,10,opt,name=UserView" json:"UserView,omitempty"`
}

func (m *PB_UserViewRowify) Reset()                    { *m = PB_UserViewRowify{} }
func (m *PB_UserViewRowify) String() string            { return proto.CompactTextString(m) }
func (*PB_UserViewRowify) ProtoMessage()               {}
func (*PB_UserViewRowify) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{7} }

func (m *PB_UserViewRowify) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PB_UserViewRowify) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_UserViewRowify) GetUserView() *PB_UserView {
	if m != nil {
		return m.UserView
	}
	return nil
}

type PB_PostViewRowify struct {
	Id       int64        `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	PostView *PB_PostView `protobuf:"bytes,10,opt,name=PostView" json:"PostView,omitempty"`
}

func (m *PB_PostViewRowify) Reset()                    { *m = PB_PostViewRowify{} }
func (m *PB_PostViewRowify) String() string            { return proto.CompactTextString(m) }
func (*PB_PostViewRowify) ProtoMessage()               {}
func (*PB_PostViewRowify) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{8} }

func (m *PB_PostViewRowify) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PB_PostViewRowify) GetPostView() *PB_PostView {
	if m != nil {
		return m.PostView
	}
	return nil
}

// ////////// Tags /////////////
type PB_TagView struct {
	TagId         int64  `protobuf:"varint,1,opt,name=TagId" json:"TagId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Count         int32  `protobuf:"varint,3,opt,name=Count" json:"Count,omitempty"`
	TagStatusEnum int32  `protobuf:"varint,4,opt,name=TagStatusEnum" json:"TagStatusEnum,omitempty"`
	CreatedTime   int32  `protobuf:"varint,5,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
}

func (m *PB_TagView) Reset()                    { *m = PB_TagView{} }
func (m *PB_TagView) String() string            { return proto.CompactTextString(m) }
func (*PB_TagView) ProtoMessage()               {}
func (*PB_TagView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{9} }

func (m *PB_TagView) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *PB_TagView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PB_TagView) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PB_TagView) GetTagStatusEnum() int32 {
	if m != nil {
		return m.TagStatusEnum
	}
	return 0
}

func (m *PB_TagView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

type PB_TopTagWithSamplePosts struct {
	TagView      *PB_TagView    `protobuf:"bytes,1,opt,name=TagView" json:"TagView,omitempty"`
	PostViewList []*PB_PostView `protobuf:"bytes,2,rep,name=PostViewList" json:"PostViewList,omitempty"`
}

func (m *PB_TopTagWithSamplePosts) Reset()                    { *m = PB_TopTagWithSamplePosts{} }
func (m *PB_TopTagWithSamplePosts) String() string            { return proto.CompactTextString(m) }
func (*PB_TopTagWithSamplePosts) ProtoMessage()               {}
func (*PB_TopTagWithSamplePosts) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{10} }

func (m *PB_TopTagWithSamplePosts) GetTagView() *PB_TagView {
	if m != nil {
		return m.TagView
	}
	return nil
}

func (m *PB_TopTagWithSamplePosts) GetPostViewList() []*PB_PostView {
	if m != nil {
		return m.PostViewList
	}
	return nil
}

// /////////////// chats ////////////
type PB_ChatView struct {
	ChatKey            string          `protobuf:"bytes,1,opt,name=ChatKey" json:"ChatKey,omitempty"`
	RoomKey            string          `protobuf:"bytes,2,opt,name=RoomKey" json:"RoomKey,omitempty"`
	RoomTypeEnum       int32           `protobuf:"varint,3,opt,name=RoomTypeEnum" json:"RoomTypeEnum,omitempty"`
	UserId             int32           `protobuf:"varint,4,opt,name=UserId" json:"UserId,omitempty"`
	PeerUserId         int32           `protobuf:"varint,5,opt,name=PeerUserId" json:"PeerUserId,omitempty"`
	GroupId            int64           `protobuf:"varint,6,opt,name=GroupId" json:"GroupId,omitempty"`
	CreatedTime        int32           `protobuf:"varint,7,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	Seq                int32           `protobuf:"varint,8,opt,name=Seq" json:"Seq,omitempty"`
	SeenSeq            int32           `protobuf:"varint,9,opt,name=SeenSeq" json:"SeenSeq,omitempty"`
	UpdatedMs          int64           `protobuf:"varint,10,opt,name=UpdatedMs" json:"UpdatedMs,omitempty"`
	UserView           *PB_UserView    `protobuf:"bytes,200,opt,name=UserView" json:"UserView,omitempty"`
	FirstUnreadMessage *PB_MessageView `protobuf:"bytes,300,opt,name=FirstUnreadMessage" json:"FirstUnreadMessage,omitempty"`
	LastMessage        *PB_MessageView `protobuf:"bytes,301,opt,name=LastMessage" json:"LastMessage,omitempty"`
}

func (m *PB_ChatView) Reset()                    { *m = PB_ChatView{} }
func (m *PB_ChatView) String() string            { return proto.CompactTextString(m) }
func (*PB_ChatView) ProtoMessage()               {}
func (*PB_ChatView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{11} }

func (m *PB_ChatView) GetChatKey() string {
	if m != nil {
		return m.ChatKey
	}
	return ""
}

func (m *PB_ChatView) GetRoomKey() string {
	if m != nil {
		return m.RoomKey
	}
	return ""
}

func (m *PB_ChatView) GetRoomTypeEnum() int32 {
	if m != nil {
		return m.RoomTypeEnum
	}
	return 0
}

func (m *PB_ChatView) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_ChatView) GetPeerUserId() int32 {
	if m != nil {
		return m.PeerUserId
	}
	return 0
}

func (m *PB_ChatView) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *PB_ChatView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_ChatView) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PB_ChatView) GetSeenSeq() int32 {
	if m != nil {
		return m.SeenSeq
	}
	return 0
}

func (m *PB_ChatView) GetUpdatedMs() int64 {
	if m != nil {
		return m.UpdatedMs
	}
	return 0
}

func (m *PB_ChatView) GetUserView() *PB_UserView {
	if m != nil {
		return m.UserView
	}
	return nil
}

func (m *PB_ChatView) GetFirstUnreadMessage() *PB_MessageView {
	if m != nil {
		return m.FirstUnreadMessage
	}
	return nil
}

func (m *PB_ChatView) GetLastMessage() *PB_MessageView {
	if m != nil {
		return m.LastMessage
	}
	return nil
}

type PB_MessageView struct {
	ChatKey            string              `protobuf:"bytes,1,opt,name=ChatKey" json:"ChatKey,omitempty"`
	MessageId          int64               `protobuf:"varint,2,opt,name=MessageId" json:"MessageId,omitempty"`
	RoomKey            string              `protobuf:"bytes,3,opt,name=RoomKey" json:"RoomKey,omitempty"`
	UserId             int32               `protobuf:"varint,4,opt,name=UserId" json:"UserId,omitempty"`
	MessageFileId      int64               `protobuf:"varint,5,opt,name=MessageFileId" json:"MessageFileId,omitempty"`
	MessageTypeEnum    int32               `protobuf:"varint,6,opt,name=MessageTypeEnum" json:"MessageTypeEnum,omitempty"`
	Text               string              `protobuf:"bytes,7,opt,name=Text" json:"Text,omitempty"`
	CreatedTime        int32               `protobuf:"varint,8,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	Seq                int32               `protobuf:"varint,9,opt,name=Seq" json:"Seq,omitempty"`
	DeliviryStatusEnum int32               `protobuf:"varint,10,opt,name=DeliviryStatusEnum" json:"DeliviryStatusEnum,omitempty"`
	UserView           *PB_UserView        `protobuf:"bytes,200,opt,name=UserView" json:"UserView,omitempty"`
	MessageFileView    *PB_MessageFileView `protobuf:"bytes,201,opt,name=MessageFileView" json:"MessageFileView,omitempty"`
}

func (m *PB_MessageView) Reset()                    { *m = PB_MessageView{} }
func (m *PB_MessageView) String() string            { return proto.CompactTextString(m) }
func (*PB_MessageView) ProtoMessage()               {}
func (*PB_MessageView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{12} }

func (m *PB_MessageView) GetChatKey() string {
	if m != nil {
		return m.ChatKey
	}
	return ""
}

func (m *PB_MessageView) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *PB_MessageView) GetRoomKey() string {
	if m != nil {
		return m.RoomKey
	}
	return ""
}

func (m *PB_MessageView) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_MessageView) GetMessageFileId() int64 {
	if m != nil {
		return m.MessageFileId
	}
	return 0
}

func (m *PB_MessageView) GetMessageTypeEnum() int32 {
	if m != nil {
		return m.MessageTypeEnum
	}
	return 0
}

func (m *PB_MessageView) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PB_MessageView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_MessageView) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PB_MessageView) GetDeliviryStatusEnum() int32 {
	if m != nil {
		return m.DeliviryStatusEnum
	}
	return 0
}

func (m *PB_MessageView) GetUserView() *PB_UserView {
	if m != nil {
		return m.UserView
	}
	return nil
}

func (m *PB_MessageView) GetMessageFileView() *PB_MessageFileView {
	if m != nil {
		return m.MessageFileView
	}
	return nil
}

type PB_MessageFileView struct {
	MessageFileId int64  `protobuf:"varint,1,opt,name=MessageFileId" json:"MessageFileId,omitempty"`
	FileTypeEnum  int32  `protobuf:"varint,2,opt,name=FileTypeEnum" json:"FileTypeEnum,omitempty"`
	Size          int32  `protobuf:"varint,3,opt,name=Size" json:"Size,omitempty"`
	Width         int32  `protobuf:"varint,4,opt,name=Width" json:"Width,omitempty"`
	Height        int32  `protobuf:"varint,5,opt,name=Height" json:"Height,omitempty"`
	Duration      int32  `protobuf:"varint,6,opt,name=Duration" json:"Duration,omitempty"`
	Extension     string `protobuf:"bytes,7,opt,name=Extension" json:"Extension,omitempty"`
}

func (m *PB_MessageFileView) Reset()                    { *m = PB_MessageFileView{} }
func (m *PB_MessageFileView) String() string            { return proto.CompactTextString(m) }
func (*PB_MessageFileView) ProtoMessage()               {}
func (*PB_MessageFileView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{13} }

func (m *PB_MessageFileView) GetMessageFileId() int64 {
	if m != nil {
		return m.MessageFileId
	}
	return 0
}

func (m *PB_MessageFileView) GetFileTypeEnum() int32 {
	if m != nil {
		return m.FileTypeEnum
	}
	return 0
}

func (m *PB_MessageFileView) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PB_MessageFileView) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PB_MessageFileView) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PB_MessageFileView) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *PB_MessageFileView) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

// just used on storage on server
type PB_MessageTableExtra struct {
	MessageFileView *PB_MessageFileView `protobuf:"bytes,1,opt,name=MessageFileView" json:"MessageFileView,omitempty"`
}

func (m *PB_MessageTableExtra) Reset()                    { *m = PB_MessageTableExtra{} }
func (m *PB_MessageTableExtra) String() string            { return proto.CompactTextString(m) }
func (*PB_MessageTableExtra) ProtoMessage()               {}
func (*PB_MessageTableExtra) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{14} }

func (m *PB_MessageTableExtra) GetMessageFileView() *PB_MessageFileView {
	if m != nil {
		return m.MessageFileView
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_PostView)(nil), "PB_PostView")
	proto.RegisterType((*PB_MediaView)(nil), "PB_MediaView")
	proto.RegisterType((*PB_ActionView)(nil), "PB_ActionView")
	proto.RegisterType((*PB_NotifyView)(nil), "PB_NotifyView")
	proto.RegisterType((*PB_CommentView)(nil), "PB_CommentView")
	proto.RegisterType((*PB_UserView)(nil), "PB_UserView")
	proto.RegisterType((*PB_TopProfileView)(nil), "PB_TopProfileView")
	proto.RegisterType((*PB_UserViewRowify)(nil), "PB_UserViewRowify")
	proto.RegisterType((*PB_PostViewRowify)(nil), "PB_PostViewRowify")
	proto.RegisterType((*PB_TagView)(nil), "PB_TagView")
	proto.RegisterType((*PB_TopTagWithSamplePosts)(nil), "PB_TopTagWithSamplePosts")
	proto.RegisterType((*PB_ChatView)(nil), "PB_ChatView")
	proto.RegisterType((*PB_MessageView)(nil), "PB_MessageView")
	proto.RegisterType((*PB_MessageFileView)(nil), "PB_MessageFileView")
	proto.RegisterType((*PB_MessageTableExtra)(nil), "PB_MessageTableExtra")
}

func init() { proto.RegisterFile("pb_views.proto", fileDescriptor11) }

var fileDescriptor11 = []byte{
	// 1568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xdd, 0x6e, 0xe3, 0xc4,
	0x17, 0x97, 0xeb, 0xba, 0x49, 0x4e, 0x9a, 0x74, 0x77, 0xfe, 0xdd, 0xbf, 0xac, 0xaa, 0x5a, 0x45,
	0xd6, 0x02, 0x41, 0x48, 0x81, 0xed, 0x2e, 0x88, 0x1b, 0x10, 0xfd, 0x64, 0x0b, 0xed, 0x6e, 0xe4,
	0xa6, 0xac, 0xc4, 0x4d, 0xe4, 0xd4, 0xd3, 0xc4, 0x22, 0xb1, 0xb3, 0xb6, 0xd3, 0x36, 0x5c, 0xf1,
	0x10, 0x3c, 0x00, 0x0f, 0xc0, 0xf2, 0x14, 0x5c, 0x2c, 0x6f, 0x80, 0xb8, 0xe0, 0x01, 0x78, 0x0a,
	0x74, 0x66, 0xc6, 0xe3, 0x19, 0xdb, 0xdd, 0x65, 0xb9, 0xe2, 0xce, 0xe7, 0x77, 0xce, 0x19, 0x67,
	0xce, 0xf9, 0x9d, 0x0f, 0x07, 0xda, 0xf3, 0xd1, 0xf0, 0x2a, 0xa0, 0xd7, 0x49, 0x6f, 0x1e, 0x47,
	0x69, 0xb4, 0xb5, 0x31, 0x1f, 0x0d, 0x53, 0x6f, 0x34, 0xa5, 0x19, 0xd0, 0x9a, 0x8f, 0x86, 0x34,
	0x5c, 0xcc, 0xb8, 0xe8, 0xfc, 0xb0, 0x06, 0xcd, 0xfe, 0xde, 0xb0, 0x1f, 0x25, 0xe9, 0x37, 0x01,
	0xbd, 0x26, 0xff, 0x87, 0x35, 0x7c, 0x3e, 0xf6, 0x6d, 0xa3, 0x63, 0x74, 0x4d, 0x57, 0x48, 0x88,
	0x9f, 0x27, 0x34, 0x3e, 0xf6, 0xed, 0x95, 0x8e, 0xd1, 0xb5, 0x5c, 0x21, 0x91, 0x87, 0xb0, 0x8e,
	0x16, 0x83, 0xe5, 0x9c, 0x1e, 0x86, 0x8b, 0x99, 0x6d, 0x76, 0x8c, 0x6e, 0x7b, 0xa7, 0xd5, 0x53,
	0x41, 0x57, 0x33, 0x21, 0x04, 0x56, 0x07, 0xf4, 0x26, 0xb5, 0x57, 0x3b, 0x46, 0xb7, 0xe1, 0xb2,
	0x67, 0xb2, 0x05, 0x75, 0x37, 0xb8, 0x98, 0x30, 0xdc, 0x62, 0xb8, 0x94, 0xc9, 0x7d, 0x80, 0x53,
	0xea, 0x07, 0xde, 0x7e, 0xb4, 0x08, 0x53, 0x7b, 0x8d, 0xbd, 0x5e, 0x41, 0xd0, 0xf7, 0x6c, 0xe2,
	0xc5, 0xd4, 0x1f, 0x44, 0x76, 0x8d, 0x69, 0xa5, 0x4c, 0xde, 0x85, 0xf6, 0x41, 0x90, 0xe0, 0xfd,
	0xf7, 0xa3, 0xd9, 0x8c, 0x86, 0xa9, 0x5d, 0x67, 0x16, 0x05, 0x14, 0xaf, 0xf7, 0xc4, 0x4b, 0x06,
	0xde, 0xd8, 0x6e, 0xf0, 0xeb, 0x71, 0x89, 0x3c, 0x80, 0x96, 0x30, 0x49, 0xf8, 0xeb, 0x81, 0xa9,
	0x75, 0x10, 0x7f, 0xe1, 0x49, 0xf0, 0x1d, 0x15, 0x26, 0x4d, 0xfe, 0x0b, 0x73, 0x04, 0xf5, 0x18,
	0x5c, 0xa1, 0x5f, 0xe7, 0xfa, 0x1c, 0x41, 0xfd, 0xa1, 0x1f, 0xa4, 0xd4, 0x1f, 0x04, 0x33, 0x6a,
	0xb7, 0xb8, 0x3e, 0x47, 0x48, 0x07, 0x9a, 0xfb, 0x31, 0xf5, 0x32, 0x83, 0x36, 0x33, 0x50, 0x21,
	0xbc, 0xa7, 0x4b, 0xf9, 0xad, 0x45, 0xfa, 0x36, 0x58, 0xfa, 0x0a, 0x28, 0xd9, 0x86, 0xc6, 0x41,
	0xe0, 0x1f, 0xe3, 0x6f, 0xf3, 0xed, 0x9d, 0x8e, 0xd1, 0xad, 0xbb, 0x39, 0x40, 0x1c, 0x58, 0x47,
	0x21, 0xf3, 0xb1, 0x1f, 0x31, 0x03, 0x0d, 0x23, 0x8f, 0xa1, 0x7d, 0x46, 0x43, 0x9f, 0xc6, 0x48,
	0x00, 0xbc, 0x83, 0xed, 0x77, 0x8c, 0x6e, 0x73, 0x67, 0xbd, 0xd7, 0xdf, 0x1b, 0x66, 0x98, 0x5b,
	0xb0, 0x21, 0x9f, 0xc2, 0x9d, 0xec, 0x04, 0xe9, 0x47, 0x2b, 0xfc, 0x4a, 0x56, 0xe4, 0x03, 0x68,
	0xb0, 0x5c, 0x33, 0x97, 0x4b, 0xe6, 0xd2, 0x42, 0x17, 0x09, 0xba, 0xb9, 0x9e, 0x3c, 0x82, 0x96,
	0x14, 0x4e, 0x82, 0x24, 0xb5, 0xc7, 0x1d, 0xb3, 0xec, 0xa0, 0xdb, 0x38, 0xbf, 0xac, 0xc0, 0xba,
	0xaa, 0x27, 0x36, 0xd4, 0x98, 0x20, 0x8b, 0x20, 0x13, 0x6f, 0xad, 0x82, 0xbc, 0x6a, 0x4c, 0x8e,
	0x8b, 0x70, 0xdb, 0x50, 0xdb, 0x9d, 0x8e, 0x16, 0xb3, 0x63, 0x9f, 0xb1, 0xdd, 0x72, 0x33, 0x11,
	0x89, 0xc5, 0x0e, 0x95, 0x85, 0x63, 0x71, 0x62, 0x69, 0x20, 0xd9, 0x04, 0xeb, 0x79, 0xe0, 0xa7,
	0x13, 0xc1, 0x7a, 0x2e, 0x30, 0xb2, 0xd2, 0x60, 0x3c, 0x49, 0x05, 0xdd, 0x85, 0x84, 0x85, 0x75,
	0x16, 0x7c, 0x4f, 0x05, 0xc5, 0xd9, 0x33, 0x16, 0xc7, 0xc1, 0x22, 0xf6, 0xd2, 0x20, 0x0a, 0x05,
	0xb5, 0xa5, 0x8c, 0xa7, 0xef, 0x47, 0xd3, 0x28, 0x66, 0xa4, 0x6e, 0xb8, 0x5c, 0x28, 0x92, 0xad,
	0x59, 0x22, 0x9b, 0xf3, 0xd3, 0x2a, 0xb4, 0xfa, 0x7b, 0xc3, 0xdd, 0x0b, 0x3c, 0x85, 0x45, 0x6c,
	0x0b, 0xea, 0x5c, 0x92, 0x21, 0x93, 0x32, 0x9e, 0xb7, 0x7b, 0x91, 0x46, 0xb1, 0x16, 0x38, 0x15,
	0x42, 0xf2, 0x72, 0x6b, 0xad, 0x8b, 0x58, 0x6e, 0x01, 0xc5, 0x32, 0xe9, 0x53, 0x9a, 0x1d, 0xc4,
	0x03, 0xaa, 0x20, 0x4a, 0x16, 0x2c, 0xad, 0x77, 0x6d, 0x43, 0x43, 0xd4, 0xeb, 0xb1, 0xcf, 0x22,
	0x69, 0xba, 0x39, 0x80, 0xa4, 0x3f, 0x5d, 0xc4, 0xb3, 0x45, 0xfc, 0xc9, 0xe3, 0x27, 0x5e, 0x32,
	0x61, 0x31, 0x35, 0x5d, 0x0d, 0x2b, 0xc6, 0xa4, 0x5e, 0x2e, 0xc0, 0x1d, 0x68, 0xc9, 0x2b, 0xdd,
	0x5a, 0x15, 0xba, 0x09, 0xe9, 0x42, 0x3d, 0xeb, 0xbb, 0x6a, 0x31, 0x64, 0x98, 0x2b, 0xb5, 0xe4,
	0x21, 0x34, 0xc5, 0x0f, 0x56, 0xca, 0x60, 0x03, 0x8d, 0x15, 0xd8, 0x55, 0x6d, 0xb0, 0xe2, 0x8e,
	0xa2, 0xe9, 0x34, 0xba, 0x56, 0x2a, 0x6e, 0x5c, 0x55, 0x71, 0x45, 0x2b, 0xb2, 0x07, 0xf7, 0xf6,
	0xa3, 0x30, 0xa5, 0x61, 0xfa, 0xec, 0x9a, 0x86, 0x4a, 0xa1, 0x4f, 0x2a, 0xdc, 0xab, 0x4d, 0x9d,
	0x3f, 0x4d, 0x46, 0x91, 0xa7, 0x51, 0x1a, 0x5c, 0x2e, 0x33, 0x8a, 0x70, 0x29, 0xa7, 0x48, 0x26,
	0x63, 0x82, 0x8e, 0x0a, 0x04, 0xc9, 0x81, 0x22, 0x81, 0xcc, 0x32, 0x81, 0x1e, 0x40, 0x0b, 0xcf,
	0x5a, 0x4a, 0xfe, 0x70, 0x6e, 0xe8, 0xe0, 0xbf, 0xa4, 0x87, 0x4e, 0xba, 0x5a, 0x89, 0x74, 0x45,
	0xfa, 0xd4, 0x2b, 0xe8, 0x73, 0x1f, 0xe0, 0x8c, 0xd2, 0xf0, 0x2c, 0xf5, 0xd2, 0x45, 0x22, 0xca,
	0x50, 0x41, 0x8a, 0xf4, 0x82, 0xff, 0x3e, 0xbd, 0x9c, 0xbf, 0x0c, 0x68, 0xeb, 0x7a, 0x3d, 0x8e,
	0x46, 0x31, 0x8e, 0xff, 0xac, 0x75, 0xe6, 0x59, 0xa9, 0xda, 0x12, 0xf4, 0x39, 0x6b, 0x95, 0xe6,
	0x6c, 0x21, 0x8e, 0x6b, 0xe5, 0x38, 0x96, 0xa7, 0xd7, 0xc6, 0x9b, 0xa7, 0x97, 0xf3, 0xbb, 0xc5,
	0x96, 0x24, 0x19, 0xd9, 0xfc, 0x2e, 0x86, 0x76, 0x97, 0x2d, 0xa8, 0xe3, 0xd3, 0x53, 0x6f, 0x46,
	0xd9, 0x2d, 0x1b, 0xae, 0x94, 0x19, 0xc7, 0x83, 0x38, 0x49, 0x99, 0x92, 0x5f, 0x2a, 0x07, 0xd0,
	0xf3, 0xc4, 0x13, 0x4a, 0xb1, 0xff, 0x64, 0x32, 0xae, 0x58, 0x78, 0x8a, 0x24, 0xf7, 0x9a, 0x58,
	0xb1, 0x54, 0xd0, 0xd5, 0x4c, 0xc8, 0x63, 0x68, 0xa1, 0x7c, 0x42, 0xaf, 0xe8, 0x94, 0xf9, 0xd4,
	0x98, 0x4f, 0xbb, 0xa7, 0xa1, 0xae, 0x6e, 0xc4, 0xba, 0xf8, 0x95, 0x97, 0x7a, 0x78, 0xb1, 0xba,
	0xe8, 0xe2, 0x42, 0x26, 0x3d, 0x20, 0xfd, 0x38, 0xba, 0x0c, 0xa6, 0xb4, 0x1f, 0x07, 0x57, 0xde,
	0xc5, 0x92, 0x1d, 0xcb, 0xa9, 0x5c, 0xa1, 0xc1, 0xd9, 0xd2, 0x9f, 0x44, 0x21, 0x27, 0xb3, 0xe9,
	0x72, 0x01, 0xd1, 0xdd, 0x51, 0xb4, 0xe0, 0x3b, 0x52, 0xc3, 0xe5, 0x02, 0xf6, 0x7f, 0xd1, 0x84,
	0x62, 0x91, 0x5a, 0x9f, 0xf7, 0x7f, 0x1d, 0xcd, 0xed, 0x82, 0x70, 0xcc, 0xed, 0xa8, 0x6a, 0x97,
	0xa1, 0xac, 0x64, 0xa3, 0x24, 0xdb, 0xd8, 0x2e, 0x45, 0xc9, 0x4a, 0xa4, 0xb0, 0x50, 0x8e, 0x4b,
	0x0b, 0xa5, 0x4e, 0xb3, 0x49, 0x89, 0x66, 0x0f, 0xa0, 0xe5, 0xd2, 0x84, 0xad, 0x29, 0xdc, 0x24,
	0xe0, 0xed, 0x46, 0x03, 0xc9, 0x57, 0xb0, 0x89, 0xe1, 0x7d, 0x16, 0x4e, 0x83, 0x90, 0xf2, 0x42,
	0x67, 0x31, 0x7b, 0x65, 0xb0, 0x5c, 0xdc, 0xeb, 0x55, 0x69, 0xdd, 0x4a, 0x1f, 0xf2, 0x1e, 0xb4,
	0x91, 0x0e, 0x38, 0x0f, 0xaf, 0x28, 0xe3, 0xf6, 0x6f, 0x9c, 0x79, 0x05, 0x98, 0x7c, 0x08, 0x70,
	0xba, 0xc4, 0x70, 0x60, 0x34, 0xec, 0x9f, 0x57, 0x44, 0xda, 0x65, 0x80, 0xd8, 0x3b, 0x14, 0x13,
	0xe7, 0x63, 0xb8, 0xdb, 0xdf, 0x1b, 0x0e, 0xa2, 0xb9, 0xc8, 0x21, 0xe3, 0x77, 0x07, 0x56, 0xf1,
	0x67, 0x30, 0x76, 0x17, 0x6b, 0x83, 0x69, 0x9c, 0x88, 0xb9, 0x49, 0x30, 0xba, 0x0e, 0x2e, 0x97,
	0xa4, 0x0d, 0x2b, 0xb2, 0xf2, 0x57, 0x78, 0xe3, 0x56, 0xcb, 0x71, 0xa5, 0x5c, 0x8e, 0x5d, 0x5e,
	0x30, 0xac, 0x10, 0xa1, 0xe2, 0x65, 0x52, 0xeb, 0x9c, 0xb2, 0x17, 0xca, 0xde, 0x55, 0xfd, 0x42,
	0xb5, 0xe3, 0xc1, 0xeb, 0x3a, 0x9e, 0xf3, 0xa3, 0x01, 0x80, 0xf7, 0xf6, 0xc6, 0xec, 0xc2, 0x9b,
	0x60, 0x0d, 0xbc, 0xb1, 0x3c, 0x8b, 0x0b, 0xd8, 0x82, 0x94, 0x52, 0x66, 0xcf, 0x7c, 0x67, 0xc2,
	0x9c, 0xf3, 0x31, 0x64, 0x49, 0x46, 0x0c, 0xbc, 0xb1, 0x92, 0x64, 0x31, 0x80, 0x34, 0xb0, 0x18,
	0x0f, 0xab, 0xbc, 0x59, 0x25, 0x60, 0xf3, 0x6c, 0x0c, 0xbc, 0xf1, 0xf3, 0x20, 0x9d, 0x9c, 0x79,
	0xb3, 0xf9, 0x94, 0x32, 0xea, 0x92, 0x77, 0xa0, 0x26, 0x7e, 0xae, 0xc8, 0x4b, 0xb3, 0x97, 0xdf,
	0xc0, 0xcd, 0x74, 0xe4, 0x23, 0xfe, 0x41, 0x26, 0x37, 0xe0, 0x15, 0xb6, 0x01, 0xeb, 0x71, 0xd0,
	0x2c, 0x9c, 0x5f, 0x4d, 0xd6, 0xdd, 0xf6, 0x27, 0x5e, 0x9a, 0xad, 0xbf, 0xf8, 0xfc, 0x35, 0x5d,
	0xb2, 0x17, 0x35, 0xdc, 0x4c, 0x44, 0x8d, 0x1b, 0x45, 0x33, 0xd4, 0xf0, 0x98, 0x64, 0x22, 0x4e,
	0x41, 0x7c, 0x2c, 0x2c, 0x70, 0x1a, 0xa6, 0x74, 0xcd, 0x55, 0xad, 0x6b, 0xea, 0x13, 0xd6, 0x2a,
	0x4d, 0x58, 0x1b, 0x6a, 0x5f, 0xc6, 0xd1, 0x62, 0x2e, 0xa7, 0x73, 0x26, 0x16, 0x03, 0x5a, 0x2b,
	0x13, 0xec, 0x0e, 0x98, 0x67, 0xf4, 0x85, 0x58, 0xd8, 0xf0, 0x11, 0x4f, 0x63, 0x93, 0x97, 0xbe,
	0x10, 0xdd, 0x2b, 0x13, 0xb1, 0x43, 0x9f, 0xcf, 0x7d, 0x74, 0x3d, 0x4d, 0x44, 0xdb, 0xca, 0x01,
	0xf2, 0xbe, 0x42, 0xd5, 0x57, 0xc6, 0xeb, 0xb8, 0x4a, 0xbe, 0x00, 0xc2, 0x3a, 0xfb, 0x79, 0x18,
	0x53, 0xcf, 0x3f, 0xa5, 0x49, 0xe2, 0x8d, 0x29, 0x2f, 0x46, 0x31, 0x56, 0x05, 0xc6, 0xfc, 0x2a,
	0x6c, 0xc9, 0x0e, 0x34, 0xb1, 0xb0, 0x33, 0xd7, 0x97, 0xb7, 0xb8, 0xaa, 0x46, 0xce, 0x4b, 0x93,
	0x4d, 0x64, 0x45, 0xff, 0x9a, 0x4c, 0x6e, 0xe3, 0x57, 0x15, 0x33, 0x14, 0x03, 0xd9, 0x74, 0x73,
	0x40, 0xcd, 0xb3, 0xa9, 0xe7, 0xf9, 0xb6, 0x1c, 0xb2, 0xcf, 0x19, 0xe6, 0x7e, 0x14, 0x4c, 0xa9,
	0x5c, 0xb1, 0x74, 0x90, 0x74, 0x61, 0x43, 0x00, 0xda, 0x30, 0xb3, 0xdc, 0x22, 0x2c, 0xa7, 0x7f,
	0x4d, 0x99, 0xfe, 0x6f, 0x5e, 0xc2, 0x45, 0xb6, 0x1b, 0x79, 0xb6, 0x7b, 0x40, 0x0e, 0xe8, 0x34,
	0xb8, 0x0a, 0xe2, 0xa5, 0x52, 0x9d, 0x7c, 0xc1, 0xaa, 0xd0, 0xbc, 0x4d, 0x96, 0x3f, 0x97, 0x97,
	0x39, 0x12, 0x7d, 0x93, 0x37, 0xe5, 0xe6, 0xce, 0xff, 0x94, 0x3c, 0x65, 0x3a, 0xb7, 0x68, 0xec,
	0xfc, 0x61, 0x00, 0x29, 0xdb, 0x95, 0x23, 0x69, 0x54, 0x45, 0xd2, 0x81, 0x75, 0x7c, 0x92, 0x61,
	0xe4, 0xbd, 0x55, 0xc3, 0xe4, 0xe7, 0xa0, 0xa9, 0x7c, 0x0e, 0xca, 0x0f, 0xca, 0xd5, 0xea, 0x0f,
	0x4a, 0x4b, 0xfb, 0xa0, 0x54, 0x3f, 0x1e, 0xd7, 0x0a, 0x1f, 0x8f, 0xdb, 0xd0, 0x38, 0xbc, 0x49,
	0x69, 0x98, 0xa0, 0x92, 0xa7, 0x29, 0x07, 0x9c, 0x73, 0xd8, 0xcc, 0xef, 0x36, 0xf0, 0x46, 0x53,
	0x7a, 0x78, 0x93, 0xc6, 0x1e, 0xf9, 0xac, 0x1c, 0xb4, 0xb7, 0x88, 0xd9, 0xde, 0x5d, 0xa8, 0x07,
	0x71, 0x6f, 0x96, 0xf4, 0xe6, 0xa3, 0x27, 0x66, 0xdf, 0xf8, 0xd6, 0xb8, 0x19, 0xad, 0xb1, 0xff,
	0xb1, 0x1e, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x87, 0x74, 0xe1, 0xf9, 0x12, 0x00, 0x00,
}
