// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_view_social.proto

package x

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PB_PostView struct {
	PostId         int64        `protobuf:"varint,1,opt,name=PostId" json:"PostId,omitempty"`
	UserId         int32        `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
	PostTypeEnum   PostTypeEnum `protobuf:"varint,3,opt,name=PostTypeEnum,enum=PostTypeEnum" json:"PostTypeEnum,omitempty"`
	Text           string       `protobuf:"bytes,4,opt,name=Text" json:"Text,omitempty"`
	RichText       string       `protobuf:"bytes,5,opt,name=RichText" json:"RichText,omitempty"`
	MediaCount     int32        `protobuf:"varint,6,opt,name=MediaCount" json:"MediaCount,omitempty"`
	SharedTo       int32        `protobuf:"varint,7,opt,name=SharedTo" json:"SharedTo,omitempty"`
	DisableComment int32        `protobuf:"varint,8,opt,name=DisableComment" json:"DisableComment,omitempty"`
	HasTag         int32        `protobuf:"varint,9,opt,name=HasTag" json:"HasTag,omitempty"`
	CommentsCount  int32        `protobuf:"varint,10,opt,name=CommentsCount" json:"CommentsCount,omitempty"`
	LikesCount     int32        `protobuf:"varint,11,opt,name=LikesCount" json:"LikesCount,omitempty"`
	ViewsCount     int32        `protobuf:"varint,12,opt,name=ViewsCount" json:"ViewsCount,omitempty"`
	EditedTime     int32        `protobuf:"varint,13,opt,name=EditedTime" json:"EditedTime,omitempty"`
	CreatedTime    int32        `protobuf:"varint,14,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	ReSharedPostId int64        `protobuf:"varint,15,opt,name=ReSharedPostId" json:"ReSharedPostId,omitempty"`
	// With me
	DidILiked        bool            `protobuf:"varint,50,opt,name=DidILiked" json:"DidILiked,omitempty"`
	DidIReShared     bool            `protobuf:"varint,51,opt,name=DidIReShared" json:"DidIReShared,omitempty"`
	SenderUserView   *PB_UserView    `protobuf:"bytes,100,opt,name=SenderUserView" json:"SenderUserView,omitempty"`
	ReSharedUserView *PB_UserView    `protobuf:"bytes,101,opt,name=ReSharedUserView" json:"ReSharedUserView,omitempty"`
	MediaView        *PB_MediaView   `protobuf:"bytes,102,opt,name=MediaView" json:"MediaView,omitempty"`
	MediaViewList    []*PB_MediaView `protobuf:"bytes,103,rep,name=MediaViewList" json:"MediaViewList,omitempty"`
}

func (m *PB_PostView) Reset()                    { *m = PB_PostView{} }
func (m *PB_PostView) String() string            { return proto.CompactTextString(m) }
func (*PB_PostView) ProtoMessage()               {}
func (*PB_PostView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

func (m *PB_PostView) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PB_PostView) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_PostView) GetPostTypeEnum() PostTypeEnum {
	if m != nil {
		return m.PostTypeEnum
	}
	return PostTypeEnum_POST_RESHARED
}

func (m *PB_PostView) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PB_PostView) GetRichText() string {
	if m != nil {
		return m.RichText
	}
	return ""
}

func (m *PB_PostView) GetMediaCount() int32 {
	if m != nil {
		return m.MediaCount
	}
	return 0
}

func (m *PB_PostView) GetSharedTo() int32 {
	if m != nil {
		return m.SharedTo
	}
	return 0
}

func (m *PB_PostView) GetDisableComment() int32 {
	if m != nil {
		return m.DisableComment
	}
	return 0
}

func (m *PB_PostView) GetHasTag() int32 {
	if m != nil {
		return m.HasTag
	}
	return 0
}

func (m *PB_PostView) GetCommentsCount() int32 {
	if m != nil {
		return m.CommentsCount
	}
	return 0
}

func (m *PB_PostView) GetLikesCount() int32 {
	if m != nil {
		return m.LikesCount
	}
	return 0
}

func (m *PB_PostView) GetViewsCount() int32 {
	if m != nil {
		return m.ViewsCount
	}
	return 0
}

func (m *PB_PostView) GetEditedTime() int32 {
	if m != nil {
		return m.EditedTime
	}
	return 0
}

func (m *PB_PostView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_PostView) GetReSharedPostId() int64 {
	if m != nil {
		return m.ReSharedPostId
	}
	return 0
}

func (m *PB_PostView) GetDidILiked() bool {
	if m != nil {
		return m.DidILiked
	}
	return false
}

func (m *PB_PostView) GetDidIReShared() bool {
	if m != nil {
		return m.DidIReShared
	}
	return false
}

func (m *PB_PostView) GetSenderUserView() *PB_UserView {
	if m != nil {
		return m.SenderUserView
	}
	return nil
}

func (m *PB_PostView) GetReSharedUserView() *PB_UserView {
	if m != nil {
		return m.ReSharedUserView
	}
	return nil
}

func (m *PB_PostView) GetMediaView() *PB_MediaView {
	if m != nil {
		return m.MediaView
	}
	return nil
}

func (m *PB_PostView) GetMediaViewList() []*PB_MediaView {
	if m != nil {
		return m.MediaViewList
	}
	return nil
}

type PB_MediaView struct {
	MediaId       int64  `protobuf:"varint,1,opt,name=MediaId" json:"MediaId,omitempty"`
	UserId        int32  `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
	PostId        int32  `protobuf:"varint,3,opt,name=PostId" json:"PostId,omitempty"`
	AlbumId       int32  `protobuf:"varint,4,opt,name=AlbumId" json:"AlbumId,omitempty"`
	MediaTypeEnum int32  `protobuf:"varint,5,opt,name=MediaTypeEnum" json:"MediaTypeEnum,omitempty"`
	Width         int32  `protobuf:"varint,6,opt,name=Width" json:"Width,omitempty"`
	Height        int32  `protobuf:"varint,7,opt,name=Height" json:"Height,omitempty"`
	Size          int32  `protobuf:"varint,8,opt,name=Size" json:"Size,omitempty"`
	Duration      int32  `protobuf:"varint,9,opt,name=Duration" json:"Duration,omitempty"`
	Color         string `protobuf:"bytes,10,opt,name=Color" json:"Color,omitempty"`
	CreatedTime   int32  `protobuf:"varint,11,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
}

func (m *PB_MediaView) Reset()                    { *m = PB_MediaView{} }
func (m *PB_MediaView) String() string            { return proto.CompactTextString(m) }
func (*PB_MediaView) ProtoMessage()               {}
func (*PB_MediaView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1} }

func (m *PB_MediaView) GetMediaId() int64 {
	if m != nil {
		return m.MediaId
	}
	return 0
}

func (m *PB_MediaView) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_MediaView) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PB_MediaView) GetAlbumId() int32 {
	if m != nil {
		return m.AlbumId
	}
	return 0
}

func (m *PB_MediaView) GetMediaTypeEnum() int32 {
	if m != nil {
		return m.MediaTypeEnum
	}
	return 0
}

func (m *PB_MediaView) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PB_MediaView) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PB_MediaView) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PB_MediaView) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *PB_MediaView) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *PB_MediaView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

type PB_ActionView struct {
	ActionId              int64           `protobuf:"varint,1,opt,name=ActionId" json:"ActionId,omitempty"`
	ActorUserId           int32           `protobuf:"varint,2,opt,name=ActorUserId" json:"ActorUserId,omitempty"`
	ActionTypeEnum        int32           `protobuf:"varint,3,opt,name=ActionTypeEnum" json:"ActionTypeEnum,omitempty"`
	PeerUserId            int32           `protobuf:"varint,4,opt,name=PeerUserId" json:"PeerUserId,omitempty"`
	PostId                int64           `protobuf:"varint,5,opt,name=PostId" json:"PostId,omitempty"`
	CommentId             int64           `protobuf:"varint,6,opt,name=CommentId" json:"CommentId,omitempty"`
	Murmur64Hash          int64           `protobuf:"varint,7,opt,name=Murmur64Hash" json:"Murmur64Hash,omitempty"`
	CreatedTime           int32           `protobuf:"varint,8,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	ActorUserView         *PB_UserView    `protobuf:"bytes,100,opt,name=ActorUserView" json:"ActorUserView,omitempty"`
	PostView              *PB_PostView    `protobuf:"bytes,101,opt,name=PostView" json:"PostView,omitempty"`
	CommentView           *PB_CommentView `protobuf:"bytes,102,opt,name=CommentView" json:"CommentView,omitempty"`
	FollowedUserView      *PB_UserView    `protobuf:"bytes,103,opt,name=FollowedUserView" json:"FollowedUserView,omitempty"`
	ContentOwenerUserView *PB_UserView    `protobuf:"bytes,104,opt,name=ContentOwenerUserView" json:"ContentOwenerUserView,omitempty"`
}

func (m *PB_ActionView) Reset()                    { *m = PB_ActionView{} }
func (m *PB_ActionView) String() string            { return proto.CompactTextString(m) }
func (*PB_ActionView) ProtoMessage()               {}
func (*PB_ActionView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{2} }

func (m *PB_ActionView) GetActionId() int64 {
	if m != nil {
		return m.ActionId
	}
	return 0
}

func (m *PB_ActionView) GetActorUserId() int32 {
	if m != nil {
		return m.ActorUserId
	}
	return 0
}

func (m *PB_ActionView) GetActionTypeEnum() int32 {
	if m != nil {
		return m.ActionTypeEnum
	}
	return 0
}

func (m *PB_ActionView) GetPeerUserId() int32 {
	if m != nil {
		return m.PeerUserId
	}
	return 0
}

func (m *PB_ActionView) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PB_ActionView) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *PB_ActionView) GetMurmur64Hash() int64 {
	if m != nil {
		return m.Murmur64Hash
	}
	return 0
}

func (m *PB_ActionView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_ActionView) GetActorUserView() *PB_UserView {
	if m != nil {
		return m.ActorUserView
	}
	return nil
}

func (m *PB_ActionView) GetPostView() *PB_PostView {
	if m != nil {
		return m.PostView
	}
	return nil
}

func (m *PB_ActionView) GetCommentView() *PB_CommentView {
	if m != nil {
		return m.CommentView
	}
	return nil
}

func (m *PB_ActionView) GetFollowedUserView() *PB_UserView {
	if m != nil {
		return m.FollowedUserView
	}
	return nil
}

func (m *PB_ActionView) GetContentOwenerUserView() *PB_UserView {
	if m != nil {
		return m.ContentOwenerUserView
	}
	return nil
}

type PB_NotifyView struct {
	NotifyId      int64           `protobuf:"varint,1,opt,name=NotifyId" json:"NotifyId,omitempty"`
	ForUserId     int32           `protobuf:"varint,2,opt,name=ForUserId" json:"ForUserId,omitempty"`
	ActorUserId   int32           `protobuf:"varint,3,opt,name=ActorUserId" json:"ActorUserId,omitempty"`
	NotiyTypeEnum int32           `protobuf:"varint,4,opt,name=NotiyTypeEnum" json:"NotiyTypeEnum,omitempty"`
	PostId        int64           `protobuf:"varint,5,opt,name=PostId" json:"PostId,omitempty"`
	CommentId     int64           `protobuf:"varint,6,opt,name=CommentId" json:"CommentId,omitempty"`
	PeerUserId    int32           `protobuf:"varint,7,opt,name=PeerUserId" json:"PeerUserId,omitempty"`
	Murmur64Hash  int64           `protobuf:"varint,8,opt,name=Murmur64Hash" json:"Murmur64Hash,omitempty"`
	SeenStatus    int32           `protobuf:"varint,9,opt,name=SeenStatus" json:"SeenStatus,omitempty"`
	CreatedTime   int32           `protobuf:"varint,10,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	ActorUserView *PB_UserView    `protobuf:"bytes,100,opt,name=ActorUserView" json:"ActorUserView,omitempty"`
	PostView      *PB_PostView    `protobuf:"bytes,101,opt,name=PostView" json:"PostView,omitempty"`
	CommentView   *PB_CommentView `protobuf:"bytes,102,opt,name=CommentView" json:"CommentView,omitempty"`
}

func (m *PB_NotifyView) Reset()                    { *m = PB_NotifyView{} }
func (m *PB_NotifyView) String() string            { return proto.CompactTextString(m) }
func (*PB_NotifyView) ProtoMessage()               {}
func (*PB_NotifyView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{3} }

func (m *PB_NotifyView) GetNotifyId() int64 {
	if m != nil {
		return m.NotifyId
	}
	return 0
}

func (m *PB_NotifyView) GetForUserId() int32 {
	if m != nil {
		return m.ForUserId
	}
	return 0
}

func (m *PB_NotifyView) GetActorUserId() int32 {
	if m != nil {
		return m.ActorUserId
	}
	return 0
}

func (m *PB_NotifyView) GetNotiyTypeEnum() int32 {
	if m != nil {
		return m.NotiyTypeEnum
	}
	return 0
}

func (m *PB_NotifyView) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PB_NotifyView) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *PB_NotifyView) GetPeerUserId() int32 {
	if m != nil {
		return m.PeerUserId
	}
	return 0
}

func (m *PB_NotifyView) GetMurmur64Hash() int64 {
	if m != nil {
		return m.Murmur64Hash
	}
	return 0
}

func (m *PB_NotifyView) GetSeenStatus() int32 {
	if m != nil {
		return m.SeenStatus
	}
	return 0
}

func (m *PB_NotifyView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_NotifyView) GetActorUserView() *PB_UserView {
	if m != nil {
		return m.ActorUserView
	}
	return nil
}

func (m *PB_NotifyView) GetPostView() *PB_PostView {
	if m != nil {
		return m.PostView
	}
	return nil
}

func (m *PB_NotifyView) GetCommentView() *PB_CommentView {
	if m != nil {
		return m.CommentView
	}
	return nil
}

type PB_CommentView struct {
	CommentId      int64        `protobuf:"varint,1,opt,name=CommentId" json:"CommentId,omitempty"`
	UserId         int32        `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
	PostId         int64        `protobuf:"varint,3,opt,name=PostId" json:"PostId,omitempty"`
	Text           string       `protobuf:"bytes,4,opt,name=Text" json:"Text,omitempty"`
	LikesCount     int32        `protobuf:"varint,5,opt,name=LikesCount" json:"LikesCount,omitempty"`
	CreatedTime    int32        `protobuf:"varint,6,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	SenderUserView *PB_UserView `protobuf:"bytes,15,opt,name=SenderUserView" json:"SenderUserView,omitempty"`
}

func (m *PB_CommentView) Reset()                    { *m = PB_CommentView{} }
func (m *PB_CommentView) String() string            { return proto.CompactTextString(m) }
func (*PB_CommentView) ProtoMessage()               {}
func (*PB_CommentView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{4} }

func (m *PB_CommentView) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *PB_CommentView) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_CommentView) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PB_CommentView) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PB_CommentView) GetLikesCount() int32 {
	if m != nil {
		return m.LikesCount
	}
	return 0
}

func (m *PB_CommentView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_CommentView) GetSenderUserView() *PB_UserView {
	if m != nil {
		return m.SenderUserView
	}
	return nil
}

type PB_UserView struct {
	UserId             int32         `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	UserName           string        `protobuf:"bytes,2,opt,name=UserName" json:"UserName,omitempty"`
	FirstName          string        `protobuf:"bytes,4,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName           string        `protobuf:"bytes,5,opt,name=LastName" json:"LastName,omitempty"`
	UserTypeEnum       UserTypeEnum  `protobuf:"varint,6,opt,name=UserTypeEnum,enum=UserTypeEnum" json:"UserTypeEnum,omitempty"`
	UserLevelEnum      UserLevelEnum `protobuf:"varint,7,opt,name=UserLevelEnum,enum=UserLevelEnum" json:"UserLevelEnum,omitempty"`
	AvatarId           int64         `protobuf:"varint,8,opt,name=AvatarId" json:"AvatarId,omitempty"`
	ProfilePrivacyEnum int32         `protobuf:"varint,9,opt,name=ProfilePrivacyEnum" json:"ProfilePrivacyEnum,omitempty"`
	Phone              int64         `protobuf:"varint,10,opt,name=Phone" json:"Phone,omitempty"`
	About              string        `protobuf:"bytes,11,opt,name=About" json:"About,omitempty"`
	// counters 100 - 200
	FollowersCount int32 `protobuf:"varint,100,opt,name=FollowersCount" json:"FollowersCount,omitempty"`
	FollowingCount int32 `protobuf:"varint,101,opt,name=FollowingCount" json:"FollowingCount,omitempty"`
	PostsCount     int32 `protobuf:"varint,102,opt,name=PostsCount" json:"PostsCount,omitempty"`
	MediaCount     int32 `protobuf:"varint,103,opt,name=MediaCount" json:"MediaCount,omitempty"`
	LikesCount     int32 `protobuf:"varint,104,opt,name=LikesCount" json:"LikesCount,omitempty"`
	ResharedCount  int32 `protobuf:"varint,105,opt,name=ResharedCount" json:"ResharedCount,omitempty"`
	// last activities
	UserOnlineStatusEnum UserOnlineStatusEnum `protobuf:"varint,200,opt,name=UserOnlineStatusEnum,enum=UserOnlineStatusEnum" json:"UserOnlineStatusEnum,omitempty"`
	LastActiveTime       int32                `protobuf:"varint,201,opt,name=LastActiveTime" json:"LastActiveTime,omitempty"`
	// with me
	MyFollwing FollowingEnum `protobuf:"varint,300,opt,name=MyFollwing,enum=FollowingEnum" json:"MyFollwing,omitempty"`
}

func (m *PB_UserView) Reset()                    { *m = PB_UserView{} }
func (m *PB_UserView) String() string            { return proto.CompactTextString(m) }
func (*PB_UserView) ProtoMessage()               {}
func (*PB_UserView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{5} }

func (m *PB_UserView) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_UserView) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PB_UserView) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PB_UserView) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PB_UserView) GetUserTypeEnum() UserTypeEnum {
	if m != nil {
		return m.UserTypeEnum
	}
	return UserTypeEnum_USER
}

func (m *PB_UserView) GetUserLevelEnum() UserLevelEnum {
	if m != nil {
		return m.UserLevelEnum
	}
	return UserLevelEnum_LEVEL_NORMAL
}

func (m *PB_UserView) GetAvatarId() int64 {
	if m != nil {
		return m.AvatarId
	}
	return 0
}

func (m *PB_UserView) GetProfilePrivacyEnum() int32 {
	if m != nil {
		return m.ProfilePrivacyEnum
	}
	return 0
}

func (m *PB_UserView) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *PB_UserView) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *PB_UserView) GetFollowersCount() int32 {
	if m != nil {
		return m.FollowersCount
	}
	return 0
}

func (m *PB_UserView) GetFollowingCount() int32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *PB_UserView) GetPostsCount() int32 {
	if m != nil {
		return m.PostsCount
	}
	return 0
}

func (m *PB_UserView) GetMediaCount() int32 {
	if m != nil {
		return m.MediaCount
	}
	return 0
}

func (m *PB_UserView) GetLikesCount() int32 {
	if m != nil {
		return m.LikesCount
	}
	return 0
}

func (m *PB_UserView) GetResharedCount() int32 {
	if m != nil {
		return m.ResharedCount
	}
	return 0
}

func (m *PB_UserView) GetUserOnlineStatusEnum() UserOnlineStatusEnum {
	if m != nil {
		return m.UserOnlineStatusEnum
	}
	return UserOnlineStatusEnum_EXACTLY
}

func (m *PB_UserView) GetLastActiveTime() int32 {
	if m != nil {
		return m.LastActiveTime
	}
	return 0
}

func (m *PB_UserView) GetMyFollwing() FollowingEnum {
	if m != nil {
		return m.MyFollwing
	}
	return FollowingEnum_FOLLOWING_NONE
}

type PB_TopProfileView struct {
	User *PB_UserView `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
}

func (m *PB_TopProfileView) Reset()                    { *m = PB_TopProfileView{} }
func (m *PB_TopProfileView) String() string            { return proto.CompactTextString(m) }
func (*PB_TopProfileView) ProtoMessage()               {}
func (*PB_TopProfileView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{6} }

func (m *PB_TopProfileView) GetUser() *PB_UserView {
	if m != nil {
		return m.User
	}
	return nil
}

// used for list of users in like/followings/followers list
type PB_UserViewRowify struct {
	Id          int64        `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	CreatedTime int32        `protobuf:"varint,2,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
	UserView    *PB_UserView `protobuf:"bytes,10,opt,name=UserView" json:"UserView,omitempty"`
}

func (m *PB_UserViewRowify) Reset()                    { *m = PB_UserViewRowify{} }
func (m *PB_UserViewRowify) String() string            { return proto.CompactTextString(m) }
func (*PB_UserViewRowify) ProtoMessage()               {}
func (*PB_UserViewRowify) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{7} }

func (m *PB_UserViewRowify) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PB_UserViewRowify) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *PB_UserViewRowify) GetUserView() *PB_UserView {
	if m != nil {
		return m.UserView
	}
	return nil
}

// ////////// Tags /////////////
type PB_TagView struct {
	TagId         int64  `protobuf:"varint,1,opt,name=TagId" json:"TagId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Count         int32  `protobuf:"varint,3,opt,name=Count" json:"Count,omitempty"`
	TagStatusEnum int32  `protobuf:"varint,4,opt,name=TagStatusEnum" json:"TagStatusEnum,omitempty"`
	CreatedTime   int32  `protobuf:"varint,5,opt,name=CreatedTime" json:"CreatedTime,omitempty"`
}

func (m *PB_TagView) Reset()                    { *m = PB_TagView{} }
func (m *PB_TagView) String() string            { return proto.CompactTextString(m) }
func (*PB_TagView) ProtoMessage()               {}
func (*PB_TagView) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{8} }

func (m *PB_TagView) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *PB_TagView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PB_TagView) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PB_TagView) GetTagStatusEnum() int32 {
	if m != nil {
		return m.TagStatusEnum
	}
	return 0
}

func (m *PB_TagView) GetCreatedTime() int32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

type PB_TopTagWithSamplePosts struct {
	TagView      *PB_TagView    `protobuf:"bytes,1,opt,name=TagView" json:"TagView,omitempty"`
	PostViewList []*PB_PostView `protobuf:"bytes,2,rep,name=PostViewList" json:"PostViewList,omitempty"`
}

func (m *PB_TopTagWithSamplePosts) Reset()                    { *m = PB_TopTagWithSamplePosts{} }
func (m *PB_TopTagWithSamplePosts) String() string            { return proto.CompactTextString(m) }
func (*PB_TopTagWithSamplePosts) ProtoMessage()               {}
func (*PB_TopTagWithSamplePosts) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{9} }

func (m *PB_TopTagWithSamplePosts) GetTagView() *PB_TagView {
	if m != nil {
		return m.TagView
	}
	return nil
}

func (m *PB_TopTagWithSamplePosts) GetPostViewList() []*PB_PostView {
	if m != nil {
		return m.PostViewList
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_PostView)(nil), "PB_PostView")
	proto.RegisterType((*PB_MediaView)(nil), "PB_MediaView")
	proto.RegisterType((*PB_ActionView)(nil), "PB_ActionView")
	proto.RegisterType((*PB_NotifyView)(nil), "PB_NotifyView")
	proto.RegisterType((*PB_CommentView)(nil), "PB_CommentView")
	proto.RegisterType((*PB_UserView)(nil), "PB_UserView")
	proto.RegisterType((*PB_TopProfileView)(nil), "PB_TopProfileView")
	proto.RegisterType((*PB_UserViewRowify)(nil), "PB_UserViewRowify")
	proto.RegisterType((*PB_TagView)(nil), "PB_TagView")
	proto.RegisterType((*PB_TopTagWithSamplePosts)(nil), "PB_TopTagWithSamplePosts")
}

func init() { proto.RegisterFile("pb_view_social.proto", fileDescriptor11) }

var fileDescriptor11 = []byte{
	// 1238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xd1, 0x8e, 0xdb, 0x44,
	0x14, 0x95, 0x93, 0xf5, 0x26, 0xb9, 0xd9, 0x64, 0xe9, 0x68, 0x8b, 0xac, 0x55, 0x55, 0x45, 0x51,
	0x81, 0x48, 0x48, 0x81, 0x6e, 0x0b, 0xe2, 0x75, 0xb3, 0x6d, 0xd5, 0x45, 0xdb, 0x36, 0x9a, 0x04,
	0x2a, 0xf1, 0x12, 0x39, 0xeb, 0xd9, 0x64, 0x44, 0x62, 0x47, 0xb6, 0xb3, 0xdb, 0xf0, 0xc4, 0x47,
	0xf0, 0x01, 0x7c, 0x00, 0xe2, 0x3b, 0xe0, 0x0f, 0x78, 0xe2, 0x03, 0xf8, 0x0a, 0x74, 0xef, 0x8c,
	0xc7, 0x1e, 0x3b, 0x15, 0x88, 0x27, 0xde, 0x72, 0xce, 0xbd, 0x33, 0x9e, 0xb9, 0x73, 0xce, 0xcc,
	0x0d, 0x9c, 0x6c, 0xe6, 0xb3, 0x5b, 0x29, 0xee, 0x66, 0x49, 0x74, 0x2d, 0xfd, 0xd5, 0x70, 0x13,
	0x47, 0x69, 0x74, 0x7a, 0xbc, 0x99, 0xcf, 0x52, 0x7f, 0xbe, 0x12, 0x89, 0x26, 0xba, 0x3a, 0x2d,
	0xc3, 0x9d, 0xcd, 0x7c, 0x26, 0xc2, 0xed, 0x5a, 0xc1, 0xfe, 0x8f, 0x87, 0xd0, 0x1e, 0x8f, 0x66,
	0xe3, 0x28, 0x49, 0xbf, 0x95, 0xe2, 0x8e, 0x7d, 0x08, 0x87, 0xf8, 0xfb, 0x32, 0xf0, 0x9c, 0x9e,
	0x33, 0xa8, 0x73, 0x8d, 0x90, 0xff, 0x26, 0x11, 0xf1, 0x65, 0xe0, 0xd5, 0x7a, 0xce, 0xc0, 0xe5,
	0x1a, 0xb1, 0xc7, 0x70, 0x84, 0x19, 0xd3, 0xdd, 0x46, 0x3c, 0x0f, 0xb7, 0x6b, 0xaf, 0xde, 0x73,
	0x06, 0xdd, 0xb3, 0xce, 0xb0, 0x48, 0x72, 0x2b, 0x85, 0x31, 0x38, 0x98, 0x8a, 0x77, 0xa9, 0x77,
	0xd0, 0x73, 0x06, 0x2d, 0x4e, 0xbf, 0xd9, 0x29, 0x34, 0xb9, 0xbc, 0x5e, 0x12, 0xef, 0x12, 0x6f,
	0x30, 0x7b, 0x08, 0xf0, 0x4a, 0x04, 0xd2, 0xbf, 0x88, 0xb6, 0x61, 0xea, 0x1d, 0xd2, 0xe7, 0x0b,
	0x0c, 0x8e, 0x9d, 0x2c, 0xfd, 0x58, 0x04, 0xd3, 0xc8, 0x6b, 0x50, 0xd4, 0x60, 0xf6, 0x31, 0x74,
	0x9f, 0xc9, 0x04, 0xeb, 0x71, 0x11, 0xad, 0xd7, 0x22, 0x4c, 0xbd, 0x26, 0x65, 0x94, 0x58, 0xdc,
	0xde, 0x4b, 0x3f, 0x99, 0xfa, 0x0b, 0xaf, 0xa5, 0xb6, 0xa7, 0x10, 0x7b, 0x04, 0x1d, 0x9d, 0x92,
	0xa8, 0xcf, 0x03, 0x85, 0x6d, 0x12, 0x57, 0x78, 0x25, 0xbf, 0x17, 0x3a, 0xa5, 0xad, 0x56, 0x98,
	0x33, 0x18, 0xc7, 0xe2, 0xea, 0xf8, 0x91, 0x8a, 0xe7, 0x0c, 0xc6, 0x9f, 0x07, 0x32, 0x15, 0xc1,
	0x54, 0xae, 0x85, 0xd7, 0x51, 0xf1, 0x9c, 0x61, 0x3d, 0x68, 0x5f, 0xc4, 0xc2, 0xcf, 0x12, 0xba,
	0x94, 0x50, 0xa4, 0x70, 0x9f, 0x5c, 0xa8, 0x5d, 0xeb, 0xe3, 0x3b, 0xa6, 0xe3, 0x2b, 0xb1, 0xec,
	0x01, 0xb4, 0x9e, 0xc9, 0xe0, 0x12, 0xd7, 0x16, 0x78, 0x67, 0x3d, 0x67, 0xd0, 0xe4, 0x39, 0xc1,
	0xfa, 0x70, 0x84, 0x20, 0x1b, 0xe3, 0x3d, 0xa1, 0x04, 0x8b, 0x63, 0x4f, 0xa1, 0x3b, 0x11, 0x61,
	0x20, 0x62, 0x14, 0x00, 0xee, 0xc1, 0x0b, 0x7a, 0xce, 0xa0, 0x7d, 0x76, 0x34, 0x1c, 0x8f, 0x66,
	0x19, 0xc7, 0x4b, 0x39, 0xec, 0x2b, 0xf8, 0x20, 0x9b, 0xc1, 0x8c, 0x13, 0x7b, 0xc6, 0x55, 0xb2,
	0xd8, 0xa7, 0xd0, 0xa2, 0xb3, 0xa6, 0x21, 0x37, 0x34, 0xa4, 0x83, 0x43, 0x0c, 0xc9, 0xf3, 0x38,
	0x7b, 0x02, 0x1d, 0x03, 0xae, 0x64, 0x92, 0x7a, 0x8b, 0x5e, 0xbd, 0x3a, 0xc0, 0xce, 0xe9, 0xff,
	0x5a, 0x83, 0xa3, 0x62, 0x9c, 0x79, 0xd0, 0x20, 0x60, 0x4c, 0x90, 0xc1, 0xf7, 0xba, 0x20, 0x77,
	0x4d, 0x5d, 0xf1, 0xba, 0xdc, 0x1e, 0x34, 0xce, 0x57, 0xf3, 0xed, 0xfa, 0x32, 0x20, 0xb5, 0xbb,
	0x3c, 0x83, 0x28, 0x2c, 0x9a, 0xd4, 0x18, 0xc7, 0x55, 0xc2, 0xb2, 0x48, 0x76, 0x02, 0xee, 0x5b,
	0x19, 0xa4, 0x4b, 0xad, 0x7a, 0x05, 0x48, 0xac, 0x42, 0x2e, 0x96, 0xa9, 0x96, 0xbb, 0x46, 0x68,
	0xac, 0x89, 0xfc, 0x41, 0x68, 0x89, 0xd3, 0x6f, 0x34, 0xc7, 0xb3, 0x6d, 0xec, 0xa7, 0x32, 0x0a,
	0xb5, 0xb4, 0x0d, 0xc6, 0xd9, 0x2f, 0xa2, 0x55, 0x14, 0x93, 0xa8, 0x5b, 0x5c, 0x81, 0xb2, 0xd8,
	0xda, 0x15, 0xb1, 0xf5, 0x7f, 0x3e, 0x80, 0xce, 0x78, 0x34, 0x3b, 0xbf, 0xc6, 0x59, 0xa8, 0x62,
	0xa7, 0xd0, 0x54, 0xc8, 0x94, 0xcc, 0x60, 0x9c, 0xef, 0xfc, 0x3a, 0x8d, 0x62, 0xab, 0x70, 0x45,
	0x0a, 0xc5, 0xab, 0xb2, 0xad, 0x5b, 0xc4, 0xe5, 0x25, 0x16, 0x6d, 0x32, 0x16, 0x22, 0x9b, 0x48,
	0x15, 0xb4, 0xc0, 0x14, 0x4e, 0xc1, 0xb5, 0xee, 0xae, 0x07, 0xd0, 0xd2, 0x7e, 0xbd, 0x0c, 0xa8,
	0x92, 0x75, 0x9e, 0x13, 0x28, 0xfa, 0x57, 0xdb, 0x78, 0xbd, 0x8d, 0xbf, 0x7c, 0xfa, 0xd2, 0x4f,
	0x96, 0x54, 0xd3, 0x3a, 0xb7, 0xb8, 0x72, 0x4d, 0x9a, 0x55, 0x03, 0x9e, 0x41, 0xc7, 0x6c, 0xe9,
	0xbd, 0xae, 0xb0, 0x53, 0xd8, 0x00, 0x9a, 0xd9, 0xbd, 0x5b, 0x34, 0x43, 0xc6, 0x71, 0x13, 0x65,
	0x8f, 0xa1, 0xad, 0x17, 0x5c, 0xb0, 0xc1, 0x31, 0x26, 0x17, 0x68, 0x5e, 0xcc, 0x41, 0xc7, 0xbd,
	0x88, 0x56, 0xab, 0xe8, 0xae, 0xe0, 0xb8, 0xc5, 0x3e, 0xc7, 0x95, 0xb3, 0xd8, 0x08, 0xee, 0x5f,
	0x44, 0x61, 0x2a, 0xc2, 0xf4, 0xcd, 0x9d, 0x08, 0x0b, 0x46, 0x5f, 0xee, 0x19, 0xbe, 0x3f, 0xb5,
	0xff, 0x67, 0x9d, 0x24, 0xf2, 0x3a, 0x4a, 0xe5, 0xcd, 0x2e, 0x93, 0x88, 0x42, 0xb9, 0x44, 0x32,
	0x8c, 0x07, 0xf4, 0xa2, 0x24, 0x90, 0x9c, 0x28, 0x0b, 0xa8, 0x5e, 0x15, 0xd0, 0x23, 0xe8, 0xe0,
	0x5c, 0x3b, 0xa3, 0x1f, 0xa5, 0x0d, 0x9b, 0xfc, 0x8f, 0xf2, 0xb0, 0x45, 0xd7, 0xa8, 0x88, 0xae,
	0x2c, 0x9f, 0xe6, 0x1e, 0xf9, 0x3c, 0x04, 0x98, 0x08, 0x11, 0x4e, 0x52, 0x3f, 0xdd, 0x26, 0xda,
	0x86, 0x05, 0xa6, 0x2c, 0x2f, 0xf8, 0xff, 0xcb, 0xab, 0xff, 0x97, 0x03, 0x5d, 0x3b, 0x6e, 0xd7,
	0xd1, 0x29, 0xd7, 0xf1, 0xdf, 0x5d, 0x9d, 0xf9, 0xa9, 0xec, 0xeb, 0x12, 0xec, 0x77, 0xd6, 0xad,
	0xbc, 0xb3, 0xa5, 0x3a, 0x1e, 0x56, 0xeb, 0x58, 0x7d, 0xbd, 0x8e, 0xff, 0xf9, 0xf5, 0xea, 0xff,
	0xe1, 0x52, 0x93, 0x64, 0x2a, 0x9b, 0xef, 0xc5, 0xb1, 0xf6, 0x72, 0x0a, 0x4d, 0xfc, 0xf5, 0xda,
	0x5f, 0x0b, 0xda, 0x65, 0x8b, 0x1b, 0x4c, 0x1a, 0x97, 0x71, 0x92, 0x52, 0x50, 0x6d, 0x2a, 0x27,
	0x70, 0xe4, 0x95, 0xaf, 0x83, 0xba, 0xff, 0xc9, 0x30, 0xb6, 0x58, 0x38, 0x8b, 0x11, 0xf7, 0xa1,
	0x6e, 0xb1, 0x8a, 0x24, 0xb7, 0x52, 0xd8, 0x53, 0xe8, 0x20, 0xbe, 0x12, 0xb7, 0x62, 0x45, 0x63,
	0x1a, 0x34, 0xa6, 0x3b, 0xb4, 0x58, 0x6e, 0x27, 0xd1, 0x2d, 0x7e, 0xeb, 0xa7, 0x3e, 0x6e, 0xac,
	0xa9, 0x6f, 0x71, 0x8d, 0xd9, 0x10, 0xd8, 0x38, 0x8e, 0x6e, 0xe4, 0x4a, 0x8c, 0x63, 0x79, 0xeb,
	0x5f, 0xef, 0x68, 0x5a, 0x25, 0xe5, 0x3d, 0x11, 0x7c, 0x5b, 0xc6, 0xcb, 0x28, 0x54, 0x62, 0xae,
	0x73, 0x05, 0x90, 0x3d, 0x9f, 0x47, 0x5b, 0xd5, 0x23, 0xb5, 0xb8, 0x02, 0x78, 0xff, 0xeb, 0x4b,
	0x28, 0xd6, 0x47, 0x1b, 0xa8, 0xfb, 0xdf, 0x66, 0xf3, 0x3c, 0x19, 0x2e, 0x54, 0x9e, 0x28, 0xe6,
	0x65, 0x2c, 0x59, 0x36, 0x4a, 0xb2, 0x8e, 0xed, 0x46, 0x5b, 0xd6, 0x30, 0xa5, 0x86, 0x72, 0x51,
	0x69, 0x28, 0x6d, 0x99, 0x2d, 0x2b, 0x32, 0x7b, 0x04, 0x1d, 0x2e, 0x12, 0x6a, 0x53, 0x54, 0x8a,
	0x54, 0xd7, 0x8d, 0x45, 0xb2, 0xaf, 0xe1, 0x04, 0xcb, 0xfb, 0x26, 0x5c, 0xc9, 0x50, 0x28, 0xa3,
	0x53, 0xcd, 0x7e, 0x73, 0xe8, 0x2c, 0xee, 0x0f, 0xf7, 0x45, 0xf9, 0xde, 0x31, 0xec, 0x13, 0xe8,
	0xa2, 0x1c, 0xf0, 0x3d, 0xbc, 0x15, 0xa4, 0xed, 0xdf, 0x95, 0xf2, 0x4a, 0x34, 0xfb, 0x0c, 0xe0,
	0xd5, 0x0e, 0xcb, 0x81, 0xd5, 0xf0, 0x7e, 0xa9, 0xe9, 0x63, 0x37, 0x05, 0xa2, 0x6f, 0x14, 0x52,
	0xfa, 0x5f, 0xc0, 0xbd, 0xf1, 0x68, 0x36, 0x8d, 0x36, 0xfa, 0x0c, 0x49, 0xdf, 0x3d, 0x38, 0xc0,
	0x65, 0x90, 0xba, 0xcb, 0xde, 0xa0, 0x48, 0x3f, 0xa2, 0x61, 0x86, 0x8c, 0xee, 0xe4, 0xcd, 0x8e,
	0x75, 0xa1, 0x66, 0x9c, 0x5f, 0x53, 0x17, 0x77, 0xd1, 0x8e, 0xb5, 0xaa, 0x1d, 0x07, 0xca, 0x30,
	0x64, 0x44, 0xd8, 0xf3, 0x31, 0x13, 0xed, 0xff, 0xe4, 0x00, 0xe0, 0x42, 0xfd, 0x05, 0xad, 0xf0,
	0x04, 0xdc, 0xa9, 0xbf, 0x30, 0x5f, 0x53, 0x00, 0xef, 0x8c, 0x82, 0xf7, 0xe8, 0xb7, 0x6a, 0x72,
	0xf0, 0x90, 0xd4, 0xbb, 0xe1, 0x9a, 0x23, 0x9c, 0xfa, 0x8b, 0xc2, 0xa9, 0xe8, 0x17, 0xc3, 0x22,
	0xcb, 0x1b, 0x70, 0xab, 0xad, 0x50, 0x02, 0x9e, 0x2a, 0xdf, 0xd4, 0x5f, 0xbc, 0x95, 0xe9, 0x72,
	0xe2, 0xaf, 0x37, 0x2b, 0x41, 0x5a, 0x63, 0x1f, 0x41, 0x43, 0x2f, 0x57, 0x17, 0xb2, 0x3d, 0xcc,
	0x77, 0xc0, 0xb3, 0x18, 0xfb, 0x5c, 0xfd, 0x83, 0x32, 0x2d, 0x6b, 0x8d, 0x5a, 0x56, 0xfb, 0xaa,
	0xb6, 0x32, 0x46, 0xf7, 0xa0, 0x29, 0xe3, 0xe1, 0x3a, 0x19, 0x6e, 0xe6, 0x2f, 0xeb, 0x63, 0xe7,
	0x3b, 0xe7, 0xdd, 0xfc, 0x90, 0xfe, 0xcd, 0x3d, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xd2,
	0xd4, 0x06, 0x15, 0x0e, 0x00, 0x00,
}
