package x

// GENERATED BY XO. DO NOT EDIT.
import (
	"errors"
	"strings"
	//"time"
	"strconv"

	"github.com/jmoiron/sqlx"
)

// (shortname .TableNameGo "err" "res" "sqlstr" "db" "XOLog") -}}//(schema .Schema .Table.TableName) -}}// .TableNameGo}}// FollowingListMemberRemoved represents a row from 'sun.following_list_member_removed'.

// Manualy copy this to project
type FollowingListMemberRemoved__ struct {
	Id               int `json:"Id"`               // Id -
	ListId           int `json:"ListId"`           // ListId -
	UserId           int `json:"UserId"`           // UserId -
	UnFollowedUserId int `json:"UnFollowedUserId"` // UnFollowedUserId -
	UpdatedTime      int `json:"UpdatedTime"`      // UpdatedTime -
	// xo fields
	_exists, _deleted bool
}

// Exists determines if the FollowingListMemberRemoved exists in the database.
func (flmr *FollowingListMemberRemoved) Exists() bool {
	return flmr._exists
}

// Deleted provides information if the FollowingListMemberRemoved has been deleted from the database.
func (flmr *FollowingListMemberRemoved) Deleted() bool {
	return flmr._deleted
}

// Insert inserts the FollowingListMemberRemoved to the database.
func (flmr *FollowingListMemberRemoved) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if flmr._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO sun.following_list_member_removed (` +
		`ListId, UserId, UnFollowedUserId, UpdatedTime` +
		`) VALUES (` +
		`?, ?, ?, ?` +
		`)`

	// run query
	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, flmr.ListId, flmr.UserId, flmr.UnFollowedUserId, flmr.UpdatedTime)
	}
	res, err := db.Exec(sqlstr, flmr.ListId, flmr.UserId, flmr.UnFollowedUserId, flmr.UpdatedTime)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return err
	}

	// set primary key and existence
	flmr.Id = int(id)
	flmr._exists = true

	OnFollowingListMemberRemoved_AfterInsert(flmr)

	return nil
}

// Insert inserts the FollowingListMemberRemoved to the database.
func (flmr *FollowingListMemberRemoved) Replace(db XODB) error {
	var err error

	// sql query

	const sqlstr = `REPLACE INTO sun.following_list_member_removed (` +
		`ListId, UserId, UnFollowedUserId, UpdatedTime` +
		`) VALUES (` +
		`?, ?, ?, ?` +
		`)`

	// run query
	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, flmr.ListId, flmr.UserId, flmr.UnFollowedUserId, flmr.UpdatedTime)
	}
	res, err := db.Exec(sqlstr, flmr.ListId, flmr.UserId, flmr.UnFollowedUserId, flmr.UpdatedTime)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return err
	}

	// set primary key and existence
	flmr.Id = int(id)
	flmr._exists = true

	OnFollowingListMemberRemoved_AfterInsert(flmr)

	return nil
}

// Update updates the FollowingListMemberRemoved in the database.
func (flmr *FollowingListMemberRemoved) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !flmr._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if flmr._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE sun.following_list_member_removed SET ` +
		`ListId = ?, UserId = ?, UnFollowedUserId = ?, UpdatedTime = ?` +
		` WHERE Id = ?`

	// run query
	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, flmr.ListId, flmr.UserId, flmr.UnFollowedUserId, flmr.UpdatedTime, flmr.Id)
	}
	_, err = db.Exec(sqlstr, flmr.ListId, flmr.UserId, flmr.UnFollowedUserId, flmr.UpdatedTime, flmr.Id)

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLogErr(err)
	}
	OnFollowingListMemberRemoved_AfterUpdate(flmr)

	return err
}

// Save saves the FollowingListMemberRemoved to the database.
func (flmr *FollowingListMemberRemoved) Save(db XODB) error {
	if flmr.Exists() {
		return flmr.Update(db)
	}

	return flmr.Replace(db)
}

// Delete deletes the FollowingListMemberRemoved from the database.
func (flmr *FollowingListMemberRemoved) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !flmr._exists {
		return nil
	}

	// if deleted, bail
	if flmr._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM sun.following_list_member_removed WHERE Id = ?`

	// run query
	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, flmr.Id)
	}
	_, err = db.Exec(sqlstr, flmr.Id)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return err
	}

	// set deleted
	flmr._deleted = true

	OnFollowingListMemberRemoved_AfterDelete(flmr)

	return nil
}

////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////// Querify gen - ME /////////////////////////////////////////
//.TableNameGo= table name
// _Deleter, _Updater

// orma types
type __FollowingListMemberRemoved_Deleter struct {
	wheres      []whereClause
	whereSep    string
	dollarIndex int
	isMysql     bool
}

type __FollowingListMemberRemoved_Updater struct {
	wheres []whereClause
	// updates   map[string]interface{}
	updates     []updateCol
	whereSep    string
	dollarIndex int
	isMysql     bool
}

type __FollowingListMemberRemoved_Selector struct {
	wheres      []whereClause
	selectCol   string
	whereSep    string
	orderBy     string //" order by id desc //for ints
	limit       int
	offset      int
	dollarIndex int
	isMysql     bool
}

func NewFollowingListMemberRemoved_Deleter() *__FollowingListMemberRemoved_Deleter {
	d := __FollowingListMemberRemoved_Deleter{whereSep: " AND "}
	return &d
}

func NewFollowingListMemberRemoved_Updater() *__FollowingListMemberRemoved_Updater {
	u := __FollowingListMemberRemoved_Updater{whereSep: " AND "}
	//u.updates =  make(map[string]interface{},10)
	return &u
}

func NewFollowingListMemberRemoved_Selector() *__FollowingListMemberRemoved_Selector {
	u := __FollowingListMemberRemoved_Selector{whereSep: " AND ", selectCol: "*"}
	return &u
}

/*/// mysql or cockroach ? or $1 handlers
func (m *__FollowingListMemberRemoved_Selector)nextDollars(size int) string  {
    r := DollarsForSqlIn(size,m.dollarIndex,m.isMysql)
    m.dollarIndex += size
    return r
}

func (m *__FollowingListMemberRemoved_Selector)nextDollar() string  {
    r := DollarsForSqlIn(1,m.dollarIndex,m.isMysql)
    m.dollarIndex += 1
    return r
}

*/
/////////////////////////////// Where for all /////////////////////////////
//// for ints all selector updater, deleter

/// mysql or cockroach ? or $1 handlers
func (m *__FollowingListMemberRemoved_Deleter) nextDollars(size int) string {
	r := DollarsForSqlIn(size, m.dollarIndex, m.isMysql)
	m.dollarIndex += size
	return r
}

func (m *__FollowingListMemberRemoved_Deleter) nextDollar() string {
	r := DollarsForSqlIn(1, m.dollarIndex, m.isMysql)
	m.dollarIndex += 1
	return r
}

////////ints
func (u *__FollowingListMemberRemoved_Deleter) Or() *__FollowingListMemberRemoved_Deleter {
	u.whereSep = " OR "
	return u
}

func (u *__FollowingListMemberRemoved_Deleter) Id_In(ins []int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Deleter) Id_Ins(ins ...int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Deleter) Id_NotIn(ins []int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Deleter) Id_Eq(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) Id_NotEq(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) Id_LT(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) Id_LE(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) Id_GT(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) Id_GE(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Deleter) ListId_In(ins []int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " ListId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Deleter) ListId_Ins(ins ...int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " ListId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Deleter) ListId_NotIn(ins []int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " ListId NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Deleter) ListId_Eq(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) ListId_NotEq(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) ListId_LT(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) ListId_LE(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) ListId_GT(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) ListId_GE(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Deleter) UserId_In(ins []int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Deleter) UserId_Ins(ins ...int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Deleter) UserId_NotIn(ins []int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UserId NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Deleter) UserId_Eq(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UserId_NotEq(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UserId_LT(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UserId_LE(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UserId_GT(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UserId_GE(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Deleter) UnFollowedUserId_In(ins []int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UnFollowedUserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Deleter) UnFollowedUserId_Ins(ins ...int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UnFollowedUserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Deleter) UnFollowedUserId_NotIn(ins []int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UnFollowedUserId NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Deleter) UnFollowedUserId_Eq(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UnFollowedUserId_NotEq(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UnFollowedUserId_LT(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UnFollowedUserId_LE(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UnFollowedUserId_GT(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UnFollowedUserId_GE(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Deleter) UpdatedTime_In(ins []int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UpdatedTime IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Deleter) UpdatedTime_Ins(ins ...int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UpdatedTime IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Deleter) UpdatedTime_NotIn(ins []int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UpdatedTime NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Deleter) UpdatedTime_Eq(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UpdatedTime_NotEq(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UpdatedTime_LT(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UpdatedTime_LE(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UpdatedTime_GT(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Deleter) UpdatedTime_GE(val int) *__FollowingListMemberRemoved_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

/// mysql or cockroach ? or $1 handlers
func (m *__FollowingListMemberRemoved_Updater) nextDollars(size int) string {
	r := DollarsForSqlIn(size, m.dollarIndex, m.isMysql)
	m.dollarIndex += size
	return r
}

func (m *__FollowingListMemberRemoved_Updater) nextDollar() string {
	r := DollarsForSqlIn(1, m.dollarIndex, m.isMysql)
	m.dollarIndex += 1
	return r
}

////////ints
func (u *__FollowingListMemberRemoved_Updater) Or() *__FollowingListMemberRemoved_Updater {
	u.whereSep = " OR "
	return u
}

func (u *__FollowingListMemberRemoved_Updater) Id_In(ins []int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Updater) Id_Ins(ins ...int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Updater) Id_NotIn(ins []int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Updater) Id_Eq(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) Id_NotEq(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) Id_LT(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) Id_LE(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) Id_GT(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) Id_GE(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Updater) ListId_In(ins []int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " ListId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Updater) ListId_Ins(ins ...int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " ListId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Updater) ListId_NotIn(ins []int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " ListId NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Updater) ListId_Eq(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) ListId_NotEq(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) ListId_LT(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) ListId_LE(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) ListId_GT(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) ListId_GE(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Updater) UserId_In(ins []int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Updater) UserId_Ins(ins ...int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Updater) UserId_NotIn(ins []int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UserId NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Updater) UserId_Eq(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UserId_NotEq(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UserId_LT(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UserId_LE(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UserId_GT(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UserId_GE(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Updater) UnFollowedUserId_In(ins []int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UnFollowedUserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Updater) UnFollowedUserId_Ins(ins ...int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UnFollowedUserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Updater) UnFollowedUserId_NotIn(ins []int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UnFollowedUserId NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Updater) UnFollowedUserId_Eq(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UnFollowedUserId_NotEq(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UnFollowedUserId_LT(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UnFollowedUserId_LE(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UnFollowedUserId_GT(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UnFollowedUserId_GE(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Updater) UpdatedTime_In(ins []int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UpdatedTime IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Updater) UpdatedTime_Ins(ins ...int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UpdatedTime IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Updater) UpdatedTime_NotIn(ins []int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UpdatedTime NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Updater) UpdatedTime_Eq(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UpdatedTime_NotEq(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UpdatedTime_LT(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UpdatedTime_LE(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UpdatedTime_GT(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Updater) UpdatedTime_GE(val int) *__FollowingListMemberRemoved_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

/// mysql or cockroach ? or $1 handlers
func (m *__FollowingListMemberRemoved_Selector) nextDollars(size int) string {
	r := DollarsForSqlIn(size, m.dollarIndex, m.isMysql)
	m.dollarIndex += size
	return r
}

func (m *__FollowingListMemberRemoved_Selector) nextDollar() string {
	r := DollarsForSqlIn(1, m.dollarIndex, m.isMysql)
	m.dollarIndex += 1
	return r
}

////////ints
func (u *__FollowingListMemberRemoved_Selector) Or() *__FollowingListMemberRemoved_Selector {
	u.whereSep = " OR "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) Id_In(ins []int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Selector) Id_Ins(ins ...int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Selector) Id_NotIn(ins []int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Selector) Id_Eq(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) Id_NotEq(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) Id_LT(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) Id_LE(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) Id_GT(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) Id_GE(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Selector) ListId_In(ins []int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " ListId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Selector) ListId_Ins(ins ...int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " ListId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Selector) ListId_NotIn(ins []int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " ListId NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Selector) ListId_Eq(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) ListId_NotEq(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) ListId_LT(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) ListId_LE(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) ListId_GT(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) ListId_GE(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " ListId >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Selector) UserId_In(ins []int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Selector) UserId_Ins(ins ...int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Selector) UserId_NotIn(ins []int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UserId NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Selector) UserId_Eq(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UserId_NotEq(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UserId_LT(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UserId_LE(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UserId_GT(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UserId_GE(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UserId >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Selector) UnFollowedUserId_In(ins []int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UnFollowedUserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Selector) UnFollowedUserId_Ins(ins ...int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UnFollowedUserId IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Selector) UnFollowedUserId_NotIn(ins []int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UnFollowedUserId NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Selector) UnFollowedUserId_Eq(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UnFollowedUserId_NotEq(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UnFollowedUserId_LT(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UnFollowedUserId_LE(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UnFollowedUserId_GT(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UnFollowedUserId_GE(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UnFollowedUserId >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__FollowingListMemberRemoved_Selector) UpdatedTime_In(ins []int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UpdatedTime IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Selector) UpdatedTime_Ins(ins ...int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UpdatedTime IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__FollowingListMemberRemoved_Selector) UpdatedTime_NotIn(ins []int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " UpdatedTime NOT IN(" + u.nextDollars(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__FollowingListMemberRemoved_Selector) UpdatedTime_Eq(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime = " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UpdatedTime_NotEq(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime != " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UpdatedTime_LT(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime < " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UpdatedTime_LE(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime <= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UpdatedTime_GT(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime > " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__FollowingListMemberRemoved_Selector) UpdatedTime_GE(val int) *__FollowingListMemberRemoved_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " UpdatedTime >= " + d.nextDollar()
	d.wheres = append(d.wheres, w)

	return d
}

///// for strings //copy of above with type int -> string + rm if eq + $ms_str_cond

////////ints

////////ints

////////ints

/// End of wheres for selectors , updators, deletor

/////////////////////////////// Updater /////////////////////////////

//ints

func (u *__FollowingListMemberRemoved_Updater) Id(newVal int) *__FollowingListMemberRemoved_Updater {
	up := updateCol{" Id = " + u.nextDollar(), newVal}
	u.updates = append(u.updates, up)
	// u.updates[" Id = " + u.nextDollar()] = newVal
	return u
}

func (u *__FollowingListMemberRemoved_Updater) Id_Increment(count int) *__FollowingListMemberRemoved_Updater {
	if count > 0 {
		up := updateCol{" Id = Id+ " + u.nextDollar(), count}
		u.updates = append(u.updates, up)
		//u.updates[" Id = Id+ " + u.nextDollar()] = count
	}

	if count < 0 {
		up := updateCol{" Id = Id- " + u.nextDollar(), count}
		u.updates = append(u.updates, up)
		// u.updates[" Id = Id- " + u.nextDollar() ] = -(count) //make it positive
	}

	return u
}

//string

//ints

func (u *__FollowingListMemberRemoved_Updater) ListId(newVal int) *__FollowingListMemberRemoved_Updater {
	up := updateCol{" ListId = " + u.nextDollar(), newVal}
	u.updates = append(u.updates, up)
	// u.updates[" ListId = " + u.nextDollar()] = newVal
	return u
}

func (u *__FollowingListMemberRemoved_Updater) ListId_Increment(count int) *__FollowingListMemberRemoved_Updater {
	if count > 0 {
		up := updateCol{" ListId = ListId+ " + u.nextDollar(), count}
		u.updates = append(u.updates, up)
		//u.updates[" ListId = ListId+ " + u.nextDollar()] = count
	}

	if count < 0 {
		up := updateCol{" ListId = ListId- " + u.nextDollar(), count}
		u.updates = append(u.updates, up)
		// u.updates[" ListId = ListId- " + u.nextDollar() ] = -(count) //make it positive
	}

	return u
}

//string

//ints

func (u *__FollowingListMemberRemoved_Updater) UserId(newVal int) *__FollowingListMemberRemoved_Updater {
	up := updateCol{" UserId = " + u.nextDollar(), newVal}
	u.updates = append(u.updates, up)
	// u.updates[" UserId = " + u.nextDollar()] = newVal
	return u
}

func (u *__FollowingListMemberRemoved_Updater) UserId_Increment(count int) *__FollowingListMemberRemoved_Updater {
	if count > 0 {
		up := updateCol{" UserId = UserId+ " + u.nextDollar(), count}
		u.updates = append(u.updates, up)
		//u.updates[" UserId = UserId+ " + u.nextDollar()] = count
	}

	if count < 0 {
		up := updateCol{" UserId = UserId- " + u.nextDollar(), count}
		u.updates = append(u.updates, up)
		// u.updates[" UserId = UserId- " + u.nextDollar() ] = -(count) //make it positive
	}

	return u
}

//string

//ints

func (u *__FollowingListMemberRemoved_Updater) UnFollowedUserId(newVal int) *__FollowingListMemberRemoved_Updater {
	up := updateCol{" UnFollowedUserId = " + u.nextDollar(), newVal}
	u.updates = append(u.updates, up)
	// u.updates[" UnFollowedUserId = " + u.nextDollar()] = newVal
	return u
}

func (u *__FollowingListMemberRemoved_Updater) UnFollowedUserId_Increment(count int) *__FollowingListMemberRemoved_Updater {
	if count > 0 {
		up := updateCol{" UnFollowedUserId = UnFollowedUserId+ " + u.nextDollar(), count}
		u.updates = append(u.updates, up)
		//u.updates[" UnFollowedUserId = UnFollowedUserId+ " + u.nextDollar()] = count
	}

	if count < 0 {
		up := updateCol{" UnFollowedUserId = UnFollowedUserId- " + u.nextDollar(), count}
		u.updates = append(u.updates, up)
		// u.updates[" UnFollowedUserId = UnFollowedUserId- " + u.nextDollar() ] = -(count) //make it positive
	}

	return u
}

//string

//ints

func (u *__FollowingListMemberRemoved_Updater) UpdatedTime(newVal int) *__FollowingListMemberRemoved_Updater {
	up := updateCol{" UpdatedTime = " + u.nextDollar(), newVal}
	u.updates = append(u.updates, up)
	// u.updates[" UpdatedTime = " + u.nextDollar()] = newVal
	return u
}

func (u *__FollowingListMemberRemoved_Updater) UpdatedTime_Increment(count int) *__FollowingListMemberRemoved_Updater {
	if count > 0 {
		up := updateCol{" UpdatedTime = UpdatedTime+ " + u.nextDollar(), count}
		u.updates = append(u.updates, up)
		//u.updates[" UpdatedTime = UpdatedTime+ " + u.nextDollar()] = count
	}

	if count < 0 {
		up := updateCol{" UpdatedTime = UpdatedTime- " + u.nextDollar(), count}
		u.updates = append(u.updates, up)
		// u.updates[" UpdatedTime = UpdatedTime- " + u.nextDollar() ] = -(count) //make it positive
	}

	return u
}

//string

/////////////////////////////////////////////////////////////////////
/////////////////////// Selector ///////////////////////////////////

//Select_* can just be used with: .GetString() , .GetStringSlice(), .GetInt() ..GetIntSlice()

func (u *__FollowingListMemberRemoved_Selector) OrderBy_Id_Desc() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY Id DESC "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) OrderBy_Id_Asc() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY Id ASC "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) Select_Id() *__FollowingListMemberRemoved_Selector {
	u.selectCol = "Id"
	return u
}

func (u *__FollowingListMemberRemoved_Selector) OrderBy_ListId_Desc() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY ListId DESC "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) OrderBy_ListId_Asc() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY ListId ASC "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) Select_ListId() *__FollowingListMemberRemoved_Selector {
	u.selectCol = "ListId"
	return u
}

func (u *__FollowingListMemberRemoved_Selector) OrderBy_UserId_Desc() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY UserId DESC "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) OrderBy_UserId_Asc() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY UserId ASC "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) Select_UserId() *__FollowingListMemberRemoved_Selector {
	u.selectCol = "UserId"
	return u
}

func (u *__FollowingListMemberRemoved_Selector) OrderBy_UnFollowedUserId_Desc() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY UnFollowedUserId DESC "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) OrderBy_UnFollowedUserId_Asc() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY UnFollowedUserId ASC "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) Select_UnFollowedUserId() *__FollowingListMemberRemoved_Selector {
	u.selectCol = "UnFollowedUserId"
	return u
}

func (u *__FollowingListMemberRemoved_Selector) OrderBy_UpdatedTime_Desc() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY UpdatedTime DESC "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) OrderBy_UpdatedTime_Asc() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY UpdatedTime ASC "
	return u
}

func (u *__FollowingListMemberRemoved_Selector) Select_UpdatedTime() *__FollowingListMemberRemoved_Selector {
	u.selectCol = "UpdatedTime"
	return u
}

func (u *__FollowingListMemberRemoved_Selector) Limit(num int) *__FollowingListMemberRemoved_Selector {
	u.limit = num
	return u
}

func (u *__FollowingListMemberRemoved_Selector) Offset(num int) *__FollowingListMemberRemoved_Selector {
	u.offset = num
	return u
}

func (u *__FollowingListMemberRemoved_Selector) Order_Rand() *__FollowingListMemberRemoved_Selector {
	u.orderBy = " ORDER BY RAND() "
	return u
}

/////////////////////////  Queryer Selector  //////////////////////////////////
func (u *__FollowingListMemberRemoved_Selector) _stoSql() (string, []interface{}) {
	sqlWherrs, whereArgs := whereClusesToSql(u.wheres, u.whereSep)

	sqlstr := "SELECT " + u.selectCol + " FROM sun.following_list_member_removed"

	if len(strings.Trim(sqlWherrs, " ")) > 0 { //2 for safty
		sqlstr += " WHERE " + sqlWherrs
	}

	if u.orderBy != "" {
		sqlstr += u.orderBy
	}

	if u.limit != 0 {
		sqlstr += " LIMIT " + strconv.Itoa(u.limit)
	}

	if u.offset != 0 {
		sqlstr += " OFFSET " + strconv.Itoa(u.offset)
	}
	return sqlstr, whereArgs
}

func (u *__FollowingListMemberRemoved_Selector) GetRow(db *sqlx.DB) (*FollowingListMemberRemoved, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, whereArgs)
	}

	row := &FollowingListMemberRemoved{}
	//by Sqlx
	err = db.Get(row, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return nil, err
	}

	row._exists = true

	OnFollowingListMemberRemoved_LoadOne(row)

	return row, nil
}

func (u *__FollowingListMemberRemoved_Selector) GetRows(db *sqlx.DB) ([]*FollowingListMemberRemoved, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, whereArgs)
	}

	var rows []*FollowingListMemberRemoved
	//by Sqlx
	err = db.Unsafe().Select(&rows, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return nil, err
	}

	/*for i:=0;i< len(rows);i++ {
		rows[i]._exists = true
	}*/

	for i := 0; i < len(rows); i++ {
		rows[i]._exists = true
	}

	OnFollowingListMemberRemoved_LoadMany(rows)

	return rows, nil
}

//dep use GetRows()
func (u *__FollowingListMemberRemoved_Selector) GetRows2(db *sqlx.DB) ([]FollowingListMemberRemoved, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, whereArgs)
	}
	var rows []*FollowingListMemberRemoved
	//by Sqlx
	err = db.Unsafe().Select(&rows, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return nil, err
	}

	/*for i:=0;i< len(rows);i++ {
		rows[i]._exists = true
	}*/

	for i := 0; i < len(rows); i++ {
		rows[i]._exists = true
	}

	OnFollowingListMemberRemoved_LoadMany(rows)

	rows2 := make([]FollowingListMemberRemoved, len(rows))
	for i := 0; i < len(rows); i++ {
		cp := *rows[i]
		rows2[i] = cp
	}

	return rows2, nil
}

func (u *__FollowingListMemberRemoved_Selector) GetString(db *sqlx.DB) (string, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, whereArgs)
	}

	var res string
	//by Sqlx
	err = db.Get(&res, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return "", err
	}

	return res, nil
}

func (u *__FollowingListMemberRemoved_Selector) GetStringSlice(db *sqlx.DB) ([]string, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, whereArgs)
	}
	var rows []string
	//by Sqlx
	err = db.Select(&rows, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return nil, err
	}

	return rows, nil
}

func (u *__FollowingListMemberRemoved_Selector) GetIntSlice(db *sqlx.DB) ([]int, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, whereArgs)
	}
	var rows []int
	//by Sqlx
	err = db.Select(&rows, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return nil, err
	}

	return rows, nil
}

func (u *__FollowingListMemberRemoved_Selector) GetInt(db *sqlx.DB) (int, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, whereArgs)
	}
	var res int
	//by Sqlx
	err = db.Get(&res, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return 0, err
	}

	return res, nil
}

/////////////////////////  Queryer Update Delete //////////////////////////////////
func (u *__FollowingListMemberRemoved_Updater) Update(db XODB) (int, error) {
	var err error

	var updateArgs []interface{}
	var sqlUpdateArr []string
	/*for up, newVal := range u.updates {
	    sqlUpdateArr = append(sqlUpdateArr, up)
	    updateArgs = append(updateArgs, newVal)
	}*/
	for _, up := range u.updates {
		sqlUpdateArr = append(sqlUpdateArr, up.col)
		updateArgs = append(updateArgs, up.val)
	}
	sqlUpdate := strings.Join(sqlUpdateArr, ",")

	sqlWherrs, whereArgs := whereClusesToSql(u.wheres, u.whereSep)

	var allArgs []interface{}
	allArgs = append(allArgs, updateArgs...)
	allArgs = append(allArgs, whereArgs...)

	sqlstr := `UPDATE sun.following_list_member_removed SET ` + sqlUpdate

	if len(strings.Trim(sqlWherrs, " ")) > 0 { //2 for safty
		sqlstr += " WHERE " + sqlWherrs
	}

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, allArgs)
	}
	res, err := db.Exec(sqlstr, allArgs...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return 0, err
	}

	num, err := res.RowsAffected()
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return 0, err
	}

	return int(num), nil
}

func (d *__FollowingListMemberRemoved_Deleter) Delete(db XODB) (int, error) {
	var err error
	var wheresArr []string
	for _, w := range d.wheres {
		wheresArr = append(wheresArr, w.condition)
	}
	wheresStr := strings.Join(wheresArr, d.whereSep)

	var args []interface{}
	for _, w := range d.wheres {
		args = append(args, w.args...)
	}

	sqlstr := "DELETE FROM sun.following_list_member_removed WHERE " + wheresStr

	// run query
	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, args)
	}
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return 0, err
	}

	// retrieve id
	num, err := res.RowsAffected()
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return 0, err
	}

	return int(num), nil
}

///////////////////////// Mass insert - replace for  FollowingListMemberRemoved ////////////////

func MassInsert_FollowingListMemberRemoved(rows []FollowingListMemberRemoved, db XODB) error {
	if len(rows) == 0 {
		return errors.New("rows slice should not be empty - inserted nothing")
	}
	var err error
	ln := len(rows)
	s := "(?,?,?,?)," //`(?, ?, ?, ?),`
	insVals_ := strings.Repeat(s, ln)
	insVals := insVals_[0 : len(insVals_)-1]
	// sql query
	sqlstr := "INSERT INTO sun.following_list_member_removed (" +
		"ListId, UserId, UnFollowedUserId, UpdatedTime" +
		") VALUES " + insVals

	// run query
	vals := make([]interface{}, 0, ln*5) //5 fields

	for _, row := range rows {
		// vals = append(vals,row.UserId)
		vals = append(vals, row.ListId)
		vals = append(vals, row.UserId)
		vals = append(vals, row.UnFollowedUserId)
		vals = append(vals, row.UpdatedTime)

	}

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, " MassInsert len = ", ln, vals)
	}
	_, err = db.Exec(sqlstr, vals...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return err
	}

	return nil
}

func MassReplace_FollowingListMemberRemoved(rows []FollowingListMemberRemoved, db XODB) error {
	var err error
	ln := len(rows)
	s := "(?,?,?,?)," //`(?, ?, ?, ?),`
	insVals_ := strings.Repeat(s, ln)
	insVals := insVals_[0 : len(insVals_)-1]
	// sql query
	sqlstr := "REPLACE INTO sun.following_list_member_removed (" +
		"ListId, UserId, UnFollowedUserId, UpdatedTime" +
		") VALUES " + insVals

	// run query
	vals := make([]interface{}, 0, ln*5) //5 fields

	for _, row := range rows {
		// vals = append(vals,row.UserId)
		vals = append(vals, row.ListId)
		vals = append(vals, row.UserId)
		vals = append(vals, row.UnFollowedUserId)
		vals = append(vals, row.UpdatedTime)

	}

	if LogTableSqlReq.FollowingListMemberRemoved {
		XOLog(sqlstr, " MassReplace len = ", ln, vals)
	}
	_, err = db.Exec(sqlstr, vals...)
	if err != nil {
		if LogTableSqlReq.FollowingListMemberRemoved {
			XOLogErr(err)
		}
		return err
	}

	return nil
}

//////////////////// Play ///////////////////////////////

//

//

//

//

//
