package x

// GENERATED BY XO. DO NOT EDIT.
import (
	"errors"
	"strings"
	//"time"
	"ms/sun/shared/helper"
	"strconv"

	"github.com/jmoiron/sqlx"
) // (shortname .TableNameGo "err" "res" "sqlstr" "db" "XOLog") -}}//(schema .Schema .Table.TableName) -}}// .TableNameGo}}// XfileServiceRequestLog represents a row from 'sun_log.xfile_service_request_log'.

// Manualy copy this to project
type XfileServiceRequestLog__ struct {
	Id          int    `json:"Id"`          // Id -
	LocalSeq    int    `json:"LocalSeq"`    // LocalSeq -
	InstanceId  int    `json:"InstanceId"`  // InstanceId -
	Url         string `json:"Url"`         // Url -
	HttpCode    int    `json:"HttpCode"`    // HttpCode -
	CreatedTime string `json:"CreatedTime"` // CreatedTime -
	// xo fields
	_exists, _deleted bool
}

// Exists determines if the XfileServiceRequestLog exists in the database.
func (xsrl *XfileServiceRequestLog) Exists() bool {
	return xsrl._exists
}

// Deleted provides information if the XfileServiceRequestLog has been deleted from the database.
func (xsrl *XfileServiceRequestLog) Deleted() bool {
	return xsrl._deleted
}

// Insert inserts the XfileServiceRequestLog to the database.
func (xsrl *XfileServiceRequestLog) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if xsrl._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO sun_log.xfile_service_request_log (` +
		`Id, LocalSeq, InstanceId, Url, HttpCode, CreatedTime` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, xsrl.Id, xsrl.LocalSeq, xsrl.InstanceId, xsrl.Url, xsrl.HttpCode, xsrl.CreatedTime)
	}
	_, err = db.Exec(sqlstr, xsrl.Id, xsrl.LocalSeq, xsrl.InstanceId, xsrl.Url, xsrl.HttpCode, xsrl.CreatedTime)
	if err != nil {
		return err
	}

	// set existence
	xsrl._exists = true

	OnXfileServiceRequestLog_AfterInsert(xsrl)

	return nil
}

// Insert inserts the XfileServiceRequestLog to the database.
func (xsrl *XfileServiceRequestLog) Replace(db XODB) error {
	var err error

	// sql query

	const sqlstr = `REPLACE INTO sun_log.xfile_service_request_log (` +
		`Id, LocalSeq, InstanceId, Url, HttpCode, CreatedTime` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, xsrl.Id, xsrl.LocalSeq, xsrl.InstanceId, xsrl.Url, xsrl.HttpCode, xsrl.CreatedTime)
	}
	_, err = db.Exec(sqlstr, xsrl.Id, xsrl.LocalSeq, xsrl.InstanceId, xsrl.Url, xsrl.HttpCode, xsrl.CreatedTime)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return err
	}

	xsrl._exists = true

	OnXfileServiceRequestLog_AfterInsert(xsrl)

	return nil
}

// Update updates the XfileServiceRequestLog in the database.
func (xsrl *XfileServiceRequestLog) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !xsrl._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if xsrl._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE sun_log.xfile_service_request_log SET ` +
		`LocalSeq = ?, InstanceId = ?, Url = ?, HttpCode = ?, CreatedTime = ?` +
		` WHERE Id = ?`

	// run query
	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, xsrl.LocalSeq, xsrl.InstanceId, xsrl.Url, xsrl.HttpCode, xsrl.CreatedTime, xsrl.Id)
	}
	_, err = db.Exec(sqlstr, xsrl.LocalSeq, xsrl.InstanceId, xsrl.Url, xsrl.HttpCode, xsrl.CreatedTime, xsrl.Id)

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLogErr(err)
	}
	OnXfileServiceRequestLog_AfterUpdate(xsrl)

	return err
}

// Save saves the XfileServiceRequestLog to the database.
func (xsrl *XfileServiceRequestLog) Save(db XODB) error {
	if xsrl.Exists() {
		return xsrl.Update(db)
	}

	return xsrl.Replace(db)
}

// Delete deletes the XfileServiceRequestLog from the database.
func (xsrl *XfileServiceRequestLog) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !xsrl._exists {
		return nil
	}

	// if deleted, bail
	if xsrl._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM sun_log.xfile_service_request_log WHERE Id = ?`

	// run query
	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, xsrl.Id)
	}
	_, err = db.Exec(sqlstr, xsrl.Id)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return err
	}

	// set deleted
	xsrl._deleted = true

	OnXfileServiceRequestLog_AfterDelete(xsrl)

	return nil
}

////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////// Querify gen - ME /////////////////////////////////////////
//.TableNameGo= table name
// _Deleter, _Updater

// orma types
type __XfileServiceRequestLog_Deleter struct {
	wheres   []whereClause
	whereSep string
}

type __XfileServiceRequestLog_Updater struct {
	wheres   []whereClause
	updates  map[string]interface{}
	whereSep string
}

type __XfileServiceRequestLog_Selector struct {
	wheres    []whereClause
	selectCol string
	whereSep  string
	orderBy   string //" order by id desc //for ints
	limit     int
	offset    int
}

func NewXfileServiceRequestLog_Deleter() *__XfileServiceRequestLog_Deleter {
	d := __XfileServiceRequestLog_Deleter{whereSep: " AND "}
	return &d
}

func NewXfileServiceRequestLog_Updater() *__XfileServiceRequestLog_Updater {
	u := __XfileServiceRequestLog_Updater{whereSep: " AND "}
	u.updates = make(map[string]interface{}, 10)
	return &u
}

func NewXfileServiceRequestLog_Selector() *__XfileServiceRequestLog_Selector {
	u := __XfileServiceRequestLog_Selector{whereSep: " AND ", selectCol: "*"}
	return &u
}

/////////////////////////////// Where for all /////////////////////////////
//// for ints all selector updater, deleter

////////ints
func (u *__XfileServiceRequestLog_Deleter) Or() *__XfileServiceRequestLog_Deleter {
	u.whereSep = " OR "
	return u
}

func (u *__XfileServiceRequestLog_Deleter) Id_In(ins []int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Deleter) Id_Ins(ins ...int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Deleter) Id_NotIn(ins []int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Deleter) Id_Eq(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) Id_NotEq(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) Id_LT(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) Id_LE(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) Id_GT(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) Id_GE(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Deleter) LocalSeq_In(ins []int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " LocalSeq IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Deleter) LocalSeq_Ins(ins ...int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " LocalSeq IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Deleter) LocalSeq_NotIn(ins []int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " LocalSeq NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Deleter) LocalSeq_Eq(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) LocalSeq_NotEq(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) LocalSeq_LT(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) LocalSeq_LE(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) LocalSeq_GT(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) LocalSeq_GE(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Deleter) InstanceId_In(ins []int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " InstanceId IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Deleter) InstanceId_Ins(ins ...int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " InstanceId IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Deleter) InstanceId_NotIn(ins []int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " InstanceId NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Deleter) InstanceId_Eq(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) InstanceId_NotEq(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) InstanceId_LT(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) InstanceId_LE(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) InstanceId_GT(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) InstanceId_GE(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Deleter) HttpCode_In(ins []int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " HttpCode IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Deleter) HttpCode_Ins(ins ...int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " HttpCode IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Deleter) HttpCode_NotIn(ins []int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " HttpCode NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Deleter) HttpCode_Eq(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) HttpCode_NotEq(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) HttpCode_LT(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) HttpCode_LE(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) HttpCode_GT(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) HttpCode_GE(val int) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

////////ints
func (u *__XfileServiceRequestLog_Updater) Or() *__XfileServiceRequestLog_Updater {
	u.whereSep = " OR "
	return u
}

func (u *__XfileServiceRequestLog_Updater) Id_In(ins []int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Updater) Id_Ins(ins ...int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Updater) Id_NotIn(ins []int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Updater) Id_Eq(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) Id_NotEq(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) Id_LT(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) Id_LE(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) Id_GT(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) Id_GE(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Updater) LocalSeq_In(ins []int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " LocalSeq IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Updater) LocalSeq_Ins(ins ...int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " LocalSeq IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Updater) LocalSeq_NotIn(ins []int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " LocalSeq NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Updater) LocalSeq_Eq(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) LocalSeq_NotEq(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) LocalSeq_LT(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) LocalSeq_LE(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) LocalSeq_GT(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) LocalSeq_GE(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Updater) InstanceId_In(ins []int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " InstanceId IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Updater) InstanceId_Ins(ins ...int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " InstanceId IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Updater) InstanceId_NotIn(ins []int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " InstanceId NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Updater) InstanceId_Eq(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) InstanceId_NotEq(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) InstanceId_LT(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) InstanceId_LE(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) InstanceId_GT(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) InstanceId_GE(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Updater) HttpCode_In(ins []int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " HttpCode IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Updater) HttpCode_Ins(ins ...int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " HttpCode IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Updater) HttpCode_NotIn(ins []int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " HttpCode NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Updater) HttpCode_Eq(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) HttpCode_NotEq(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) HttpCode_LT(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) HttpCode_LE(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) HttpCode_GT(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) HttpCode_GE(val int) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

////////ints
func (u *__XfileServiceRequestLog_Selector) Or() *__XfileServiceRequestLog_Selector {
	u.whereSep = " OR "
	return u
}

func (u *__XfileServiceRequestLog_Selector) Id_In(ins []int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Selector) Id_Ins(ins ...int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Selector) Id_NotIn(ins []int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Id NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Selector) Id_Eq(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) Id_NotEq(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) Id_LT(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) Id_LE(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) Id_GT(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) Id_GE(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Id >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Selector) LocalSeq_In(ins []int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " LocalSeq IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Selector) LocalSeq_Ins(ins ...int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " LocalSeq IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Selector) LocalSeq_NotIn(ins []int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " LocalSeq NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Selector) LocalSeq_Eq(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) LocalSeq_NotEq(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) LocalSeq_LT(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) LocalSeq_LE(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) LocalSeq_GT(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) LocalSeq_GE(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " LocalSeq >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Selector) InstanceId_In(ins []int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " InstanceId IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Selector) InstanceId_Ins(ins ...int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " InstanceId IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Selector) InstanceId_NotIn(ins []int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " InstanceId NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Selector) InstanceId_Eq(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) InstanceId_NotEq(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) InstanceId_LT(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) InstanceId_LE(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) InstanceId_GT(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) InstanceId_GE(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " InstanceId >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Selector) HttpCode_In(ins []int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " HttpCode IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Selector) HttpCode_Ins(ins ...int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " HttpCode IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Selector) HttpCode_NotIn(ins []int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " HttpCode NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Selector) HttpCode_Eq(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) HttpCode_NotEq(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) HttpCode_LT(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode < ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) HttpCode_LE(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode <= ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) HttpCode_GT(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode > ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) HttpCode_GE(val int) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " HttpCode >= ? "
	d.wheres = append(d.wheres, w)

	return d
}

///// for strings //copy of above with type int -> string + rm if eq + $ms_str_cond

////////ints

func (u *__XfileServiceRequestLog_Deleter) Url_In(ins []string) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Url IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Deleter) Url_NotIn(ins []string) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Url NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

//must be used like: UserName_like("hamid%")
func (u *__XfileServiceRequestLog_Deleter) Url_Like(val string) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Url LIKE ? "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Deleter) Url_Eq(val string) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Url = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) Url_NotEq(val string) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Url != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Deleter) CreatedTime_In(ins []string) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " CreatedTime IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Deleter) CreatedTime_NotIn(ins []string) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " CreatedTime NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

//must be used like: UserName_like("hamid%")
func (u *__XfileServiceRequestLog_Deleter) CreatedTime_Like(val string) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " CreatedTime LIKE ? "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Deleter) CreatedTime_Eq(val string) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " CreatedTime = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Deleter) CreatedTime_NotEq(val string) *__XfileServiceRequestLog_Deleter {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " CreatedTime != ? "
	d.wheres = append(d.wheres, w)

	return d
}

////////ints

func (u *__XfileServiceRequestLog_Updater) Url_In(ins []string) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Url IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Updater) Url_NotIn(ins []string) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Url NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

//must be used like: UserName_like("hamid%")
func (u *__XfileServiceRequestLog_Updater) Url_Like(val string) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Url LIKE ? "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Updater) Url_Eq(val string) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Url = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) Url_NotEq(val string) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Url != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Updater) CreatedTime_In(ins []string) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " CreatedTime IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Updater) CreatedTime_NotIn(ins []string) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " CreatedTime NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

//must be used like: UserName_like("hamid%")
func (u *__XfileServiceRequestLog_Updater) CreatedTime_Like(val string) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " CreatedTime LIKE ? "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Updater) CreatedTime_Eq(val string) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " CreatedTime = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Updater) CreatedTime_NotEq(val string) *__XfileServiceRequestLog_Updater {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " CreatedTime != ? "
	d.wheres = append(d.wheres, w)

	return d
}

////////ints

func (u *__XfileServiceRequestLog_Selector) Url_In(ins []string) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Url IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Selector) Url_NotIn(ins []string) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " Url NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

//must be used like: UserName_like("hamid%")
func (u *__XfileServiceRequestLog_Selector) Url_Like(val string) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Url LIKE ? "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Selector) Url_Eq(val string) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Url = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) Url_NotEq(val string) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " Url != ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (u *__XfileServiceRequestLog_Selector) CreatedTime_In(ins []string) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " CreatedTime IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

func (u *__XfileServiceRequestLog_Selector) CreatedTime_NotIn(ins []string) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	for _, i := range ins {
		insWhere = append(insWhere, i)
	}
	w.args = insWhere
	w.condition = " CreatedTime NOT IN(" + helper.DbQuestionForSqlIn(len(ins)) + ") "
	u.wheres = append(u.wheres, w)

	return u
}

//must be used like: UserName_like("hamid%")
func (u *__XfileServiceRequestLog_Selector) CreatedTime_Like(val string) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " CreatedTime LIKE ? "
	u.wheres = append(u.wheres, w)

	return u
}

func (d *__XfileServiceRequestLog_Selector) CreatedTime_Eq(val string) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " CreatedTime = ? "
	d.wheres = append(d.wheres, w)

	return d
}

func (d *__XfileServiceRequestLog_Selector) CreatedTime_NotEq(val string) *__XfileServiceRequestLog_Selector {
	w := whereClause{}
	var insWhere []interface{}
	insWhere = append(insWhere, val)
	w.args = insWhere
	w.condition = " CreatedTime != ? "
	d.wheres = append(d.wheres, w)

	return d
}

/// End of wheres for selectors , updators, deletor

/////////////////////////////// Updater /////////////////////////////

//ints

func (u *__XfileServiceRequestLog_Updater) Id(newVal int) *__XfileServiceRequestLog_Updater {
	u.updates[" Id = ? "] = newVal
	return u
}

func (u *__XfileServiceRequestLog_Updater) Id_Increment(count int) *__XfileServiceRequestLog_Updater {
	if count > 0 {
		u.updates[" Id = Id+? "] = count
	}

	if count < 0 {
		u.updates[" Id = Id-? "] = -(count) //make it positive
	}

	return u
}

//string

//ints

func (u *__XfileServiceRequestLog_Updater) LocalSeq(newVal int) *__XfileServiceRequestLog_Updater {
	u.updates[" LocalSeq = ? "] = newVal
	return u
}

func (u *__XfileServiceRequestLog_Updater) LocalSeq_Increment(count int) *__XfileServiceRequestLog_Updater {
	if count > 0 {
		u.updates[" LocalSeq = LocalSeq+? "] = count
	}

	if count < 0 {
		u.updates[" LocalSeq = LocalSeq-? "] = -(count) //make it positive
	}

	return u
}

//string

//ints

func (u *__XfileServiceRequestLog_Updater) InstanceId(newVal int) *__XfileServiceRequestLog_Updater {
	u.updates[" InstanceId = ? "] = newVal
	return u
}

func (u *__XfileServiceRequestLog_Updater) InstanceId_Increment(count int) *__XfileServiceRequestLog_Updater {
	if count > 0 {
		u.updates[" InstanceId = InstanceId+? "] = count
	}

	if count < 0 {
		u.updates[" InstanceId = InstanceId-? "] = -(count) //make it positive
	}

	return u
}

//string

//ints

//string
func (u *__XfileServiceRequestLog_Updater) Url(newVal string) *__XfileServiceRequestLog_Updater {
	u.updates[" Url = ? "] = newVal
	return u
}

//ints

func (u *__XfileServiceRequestLog_Updater) HttpCode(newVal int) *__XfileServiceRequestLog_Updater {
	u.updates[" HttpCode = ? "] = newVal
	return u
}

func (u *__XfileServiceRequestLog_Updater) HttpCode_Increment(count int) *__XfileServiceRequestLog_Updater {
	if count > 0 {
		u.updates[" HttpCode = HttpCode+? "] = count
	}

	if count < 0 {
		u.updates[" HttpCode = HttpCode-? "] = -(count) //make it positive
	}

	return u
}

//string

//ints

//string
func (u *__XfileServiceRequestLog_Updater) CreatedTime(newVal string) *__XfileServiceRequestLog_Updater {
	u.updates[" CreatedTime = ? "] = newVal
	return u
}

/////////////////////////////////////////////////////////////////////
/////////////////////// Selector ///////////////////////////////////

//Select_* can just be used with: .GetString() , .GetStringSlice(), .GetInt() ..GetIntSlice()

func (u *__XfileServiceRequestLog_Selector) OrderBy_Id_Desc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY Id DESC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_Id_Asc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY Id ASC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) Select_Id() *__XfileServiceRequestLog_Selector {
	u.selectCol = "Id"
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_LocalSeq_Desc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY LocalSeq DESC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_LocalSeq_Asc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY LocalSeq ASC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) Select_LocalSeq() *__XfileServiceRequestLog_Selector {
	u.selectCol = "LocalSeq"
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_InstanceId_Desc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY InstanceId DESC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_InstanceId_Asc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY InstanceId ASC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) Select_InstanceId() *__XfileServiceRequestLog_Selector {
	u.selectCol = "InstanceId"
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_Url_Desc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY Url DESC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_Url_Asc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY Url ASC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) Select_Url() *__XfileServiceRequestLog_Selector {
	u.selectCol = "Url"
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_HttpCode_Desc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY HttpCode DESC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_HttpCode_Asc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY HttpCode ASC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) Select_HttpCode() *__XfileServiceRequestLog_Selector {
	u.selectCol = "HttpCode"
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_CreatedTime_Desc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY CreatedTime DESC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) OrderBy_CreatedTime_Asc() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY CreatedTime ASC "
	return u
}

func (u *__XfileServiceRequestLog_Selector) Select_CreatedTime() *__XfileServiceRequestLog_Selector {
	u.selectCol = "CreatedTime"
	return u
}

func (u *__XfileServiceRequestLog_Selector) Limit(num int) *__XfileServiceRequestLog_Selector {
	u.limit = num
	return u
}

func (u *__XfileServiceRequestLog_Selector) Offset(num int) *__XfileServiceRequestLog_Selector {
	u.offset = num
	return u
}

func (u *__XfileServiceRequestLog_Selector) Order_Rand() *__XfileServiceRequestLog_Selector {
	u.orderBy = " ORDER BY RAND() "
	return u
}

/////////////////////////  Queryer Selector  //////////////////////////////////
func (u *__XfileServiceRequestLog_Selector) _stoSql() (string, []interface{}) {
	sqlWherrs, whereArgs := whereClusesToSql(u.wheres, u.whereSep)

	sqlstr := "SELECT " + u.selectCol + " FROM sun_log.xfile_service_request_log"

	if len(strings.Trim(sqlWherrs, " ")) > 0 { //2 for safty
		sqlstr += " WHERE " + sqlWherrs
	}

	if u.orderBy != "" {
		sqlstr += u.orderBy
	}

	if u.limit != 0 {
		sqlstr += " LIMIT " + strconv.Itoa(u.limit)
	}

	if u.offset != 0 {
		sqlstr += " OFFSET " + strconv.Itoa(u.offset)
	}
	return sqlstr, whereArgs
}

func (u *__XfileServiceRequestLog_Selector) GetRow(db *sqlx.DB) (*XfileServiceRequestLog, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, whereArgs)
	}

	row := &XfileServiceRequestLog{}
	//by Sqlx
	err = db.Get(row, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return nil, err
	}

	row._exists = true

	OnXfileServiceRequestLog_LoadOne(row)

	return row, nil
}

func (u *__XfileServiceRequestLog_Selector) GetRows(db *sqlx.DB) ([]*XfileServiceRequestLog, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, whereArgs)
	}

	var rows []*XfileServiceRequestLog
	//by Sqlx
	err = db.Unsafe().Select(&rows, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return nil, err
	}

	/*for i:=0;i< len(rows);i++ {
		rows[i]._exists = true
	}*/

	for i := 0; i < len(rows); i++ {
		rows[i]._exists = true
	}

	OnXfileServiceRequestLog_LoadMany(rows)

	return rows, nil
}

//dep use GetRows()
func (u *__XfileServiceRequestLog_Selector) GetRows2(db *sqlx.DB) ([]XfileServiceRequestLog, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, whereArgs)
	}
	var rows []*XfileServiceRequestLog
	//by Sqlx
	err = db.Unsafe().Select(&rows, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return nil, err
	}

	/*for i:=0;i< len(rows);i++ {
		rows[i]._exists = true
	}*/

	for i := 0; i < len(rows); i++ {
		rows[i]._exists = true
	}

	OnXfileServiceRequestLog_LoadMany(rows)

	rows2 := make([]XfileServiceRequestLog, len(rows))
	for i := 0; i < len(rows); i++ {
		cp := *rows[i]
		rows2[i] = cp
	}

	return rows2, nil
}

func (u *__XfileServiceRequestLog_Selector) GetString(db *sqlx.DB) (string, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, whereArgs)
	}

	var res string
	//by Sqlx
	err = db.Get(&res, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return "", err
	}

	return res, nil
}

func (u *__XfileServiceRequestLog_Selector) GetStringSlice(db *sqlx.DB) ([]string, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, whereArgs)
	}
	var rows []string
	//by Sqlx
	err = db.Select(&rows, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return nil, err
	}

	return rows, nil
}

func (u *__XfileServiceRequestLog_Selector) GetIntSlice(db *sqlx.DB) ([]int, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, whereArgs)
	}
	var rows []int
	//by Sqlx
	err = db.Select(&rows, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return nil, err
	}

	return rows, nil
}

func (u *__XfileServiceRequestLog_Selector) GetInt(db *sqlx.DB) (int, error) {
	var err error

	sqlstr, whereArgs := u._stoSql()

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, whereArgs)
	}
	var res int
	//by Sqlx
	err = db.Get(&res, sqlstr, whereArgs...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return 0, err
	}

	return res, nil
}

/////////////////////////  Queryer Update Delete //////////////////////////////////
func (u *__XfileServiceRequestLog_Updater) Update(db XODB) (int, error) {
	var err error

	var updateArgs []interface{}
	var sqlUpdateArr []string
	for up, newVal := range u.updates {
		sqlUpdateArr = append(sqlUpdateArr, up)
		updateArgs = append(updateArgs, newVal)
	}
	sqlUpdate := strings.Join(sqlUpdateArr, ",")

	sqlWherrs, whereArgs := whereClusesToSql(u.wheres, u.whereSep)

	var allArgs []interface{}
	allArgs = append(allArgs, updateArgs...)
	allArgs = append(allArgs, whereArgs...)

	sqlstr := `UPDATE sun_log.xfile_service_request_log SET ` + sqlUpdate

	if len(strings.Trim(sqlWherrs, " ")) > 0 { //2 for safty
		sqlstr += " WHERE " + sqlWherrs
	}

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, allArgs)
	}
	res, err := db.Exec(sqlstr, allArgs...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return 0, err
	}

	num, err := res.RowsAffected()
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return 0, err
	}

	return int(num), nil
}

func (d *__XfileServiceRequestLog_Deleter) Delete(db XODB) (int, error) {
	var err error
	var wheresArr []string
	for _, w := range d.wheres {
		wheresArr = append(wheresArr, w.condition)
	}
	wheresStr := strings.Join(wheresArr, d.whereSep)

	var args []interface{}
	for _, w := range d.wheres {
		args = append(args, w.args...)
	}

	sqlstr := "DELETE FROM sun_log.xfile_service_request_log WHERE " + wheresStr

	// run query
	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, args)
	}
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return 0, err
	}

	// retrieve id
	num, err := res.RowsAffected()
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return 0, err
	}

	return int(num), nil
}

///////////////////////// Mass insert - replace for  XfileServiceRequestLog ////////////////

func MassInsert_XfileServiceRequestLog(rows []XfileServiceRequestLog, db XODB) error {
	if len(rows) == 0 {
		return errors.New("rows slice should not be empty - inserted nothing")
	}
	var err error
	ln := len(rows)
	//s:= "(?,?,?,?,?,?)," //`(?, ?, ?, ?),`
	s := "(?,?,?,?,?,?)," //`(?, ?, ?, ?),`
	insVals_ := strings.Repeat(s, ln)
	insVals := insVals_[0 : len(insVals_)-1]
	// sql query
	sqlstr := "INSERT INTO sun_log.xfile_service_request_log (" +
		"Id, LocalSeq, InstanceId, Url, HttpCode, CreatedTime" +
		") VALUES " + insVals

	// run query
	vals := make([]interface{}, 0, ln*5) //5 fields

	for _, row := range rows {
		// vals = append(vals,row.UserId)
		vals = append(vals, row.Id)
		vals = append(vals, row.LocalSeq)
		vals = append(vals, row.InstanceId)
		vals = append(vals, row.Url)
		vals = append(vals, row.HttpCode)
		vals = append(vals, row.CreatedTime)

	}

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, " MassInsert len = ", ln, vals)
	}
	_, err = db.Exec(sqlstr, vals...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return err
	}

	return nil
}

func MassReplace_XfileServiceRequestLog(rows []XfileServiceRequestLog, db XODB) error {
	if len(rows) == 0 {
		return errors.New("rows slice should not be empty - inserted nothing")
	}
	var err error
	ln := len(rows)
	//s:= "(?,?,?,?,?,?)," //`(?, ?, ?, ?),`
	s := "(?,?,?,?,?,?)," //`(?, ?, ?, ?),`
	insVals_ := strings.Repeat(s, ln)
	insVals := insVals_[0 : len(insVals_)-1]
	// sql query
	sqlstr := "REPLACE INTO sun_log.xfile_service_request_log (" +
		"Id, LocalSeq, InstanceId, Url, HttpCode, CreatedTime" +
		") VALUES " + insVals

	// run query
	vals := make([]interface{}, 0, ln*5) //5 fields

	for _, row := range rows {
		// vals = append(vals,row.UserId)
		vals = append(vals, row.Id)
		vals = append(vals, row.LocalSeq)
		vals = append(vals, row.InstanceId)
		vals = append(vals, row.Url)
		vals = append(vals, row.HttpCode)
		vals = append(vals, row.CreatedTime)

	}

	if LogTableSqlReq.XfileServiceRequestLog {
		XOLog(sqlstr, " MassReplace len = ", ln, vals)
	}
	_, err = db.Exec(sqlstr, vals...)
	if err != nil {
		if LogTableSqlReq.XfileServiceRequestLog {
			XOLogErr(err)
		}
		return err
	}

	return nil

}

//////////////////// Play ///////////////////////////////

//

//

//

//

//

//
